---

# files/vmware-postgres14-14.2-1.el7.x86_64.rpm
# pgbackrest_path: "/opt/vmware/postgres/14/bin/pgbackrest"
pgbackrest_path: "/usr/bin/pgbackrest"
package_name: vmware-postgres
major_version: 13
minor_version: 3
patch_version: 0
rhel_version: el7
database_name: vmware_postgres_testdb
username: postgres
patroni_path: "/usr/local/bin/patroni"
patronictl_path: "/usr/local/bin/patronictl"

# Patroni prerequistes
urllib3_ver1: 1.19.1
urllib3_ver2: 1.21
six_ver: 1.7
kazoo_ver: 1.3.1
python-etc_ver1: 0.4.3
python-etc_ver2: 0.5
python-consul_ver: 0.7.0
click_ver: 4.1
prettytable_ver: 0.7
psutil_ver: 2.0.0
kube_ver1: 2.0.0
kube_ver2: 7.0.0
kube_ver3: 4.0
kube_ver4: 5.0
