---
- name: Copy the PGWatch2 RPM Package
  copy:
    src: "pgwatch2_{{ _pgwatch2.major_version }}.{{ _pgwatch2.minor_version }}.{{ _pgwatch2.patch_version }}_linux_{{ _pgwatch2.arch }}.rpm"
    dest: "{{ pgsql.base_path }}/pgwatch2_{{ _pgwatch2.major_version }}.{{ _pgwatch2.minor_version }}.{{ _pgwatch2.patch_version }}_linux_{{ _pgwatch2.arch }}.rpm"
    mode: 0644
    owner: root
    group: root


- name: Install PGWatch2 RPM Package
  package:
    name: "{{ pgsql.base_path }}/pgwatch2_{{ _pgwatch2.major_version }}.{{ _pgwatch2.minor_version }}.{{ _pgwatch2.patch_version }}_linux_{{ _pgwatch2.arch }}.rpm"
    state: present
    disable_gpg_check: true
  async: 180
  poll: 5

