---
# Install VMWare Postgres for Red Hat / CentOS

# for now fail if it's not a Red Hat based system
- name: Check OS ( GPDB )
  fail: msg="Not a Red Hat based system!"
  when: ansible_os_family != 'RedHat' or ansible_os_family != 'CentOS' or  ansible_os_family != 'Rocky'

#
- name: Install pgwatch2
  import_tasks: install.yml
  tags: install
  # when: install_pgwatch2 == true and inventory_hostname in groups['monitors']

#
- name: Uninstall pgwatch2
  import_tasks: uninstall.yml
  tags: uninstall
  # when: uninstall_pgwatch2 == true and inventory_hostname in groups['monitors']

#
- name: Upgrade pgwatch2
  import_tasks: upgrade.yml
  tags: upgrade
  # when: inventory_hostname in groups['monitors']
