---
- name: Alternative Python Version
  shell: |
    update-alternatives --install /usr/bin/python python {{ yum_python_version }} 1
    alternatives --set python {{ yum_python_version }}
  register: alternative_python2_version


- name: Install the Prerequisties RPM Packages for VMware Postgres Patroni
  package:
    name: "{{ rh_install_pkgs }}"
    state: present
  async: 180
  poll: 5
  register: install_prereq_pkgs
  vars:
    ansible_python_interpreter: "{{ yum_python_version }}"


- name: Install the Python RPM Packages for VMware Postgres Patroni
  package:
    name: "{{ rh7_python_pkgs }}"
    state: present
    skip_broken: yes
  async: 180
  poll: 5
  vars:
    ansible_python_interpreter: "{{ yum_python_version }}"
  when: hostvars[inventory_hostname].ansible_distribution_major_version|int <= 7


- name: Install the Python RPM Packages for VMware Postgres Patroni
  package:
    name: "{{ rh8_python_pkgs }}"
    state: present
    skip_broken: yes
  async: 180
  poll: 5
  register: install_python3
  vars:
    ansible_python_interpreter: "{{ yum_python_version }}"
  when: hostvars[inventory_hostname].ansible_distribution_major_version|int == 8


- name: Install the Python RPM Packages for VMware Postgres Patroni
  package:
    name: "{{ rh9_python_pkgs }}"
    state: present
    skip_broken: yes
  async: 180
  poll: 5
  register: install_python311
  vars:
    ansible_python_interpreter: "{{ yum_python_version }}"
  when: hostvars[inventory_hostname].ansible_distribution_major_version|int >= 9
# alternatives --set python /usr/bin/python3
# update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.9 3
# update-alternatives --install /usr/bin/unversioned-python python /usr/bin/python3.9 1

