---
- name: Change Permission of /home/postgres Directory
  shell: |
    chown -R postgres.postgres {{ pgsql.home_dir }}
  register: change_permission
  ignore_errors: yes


- name: Setup and Configure the Python Module Dependencies for ETCD for Workers
  template: src=requirements.txt.{{ pgsql.os_version }}.j2 dest={{ pgsql.base_dir }}/requirements.txt owner=postgres group=postgres mode=644 force=yes
  register: install_patroni_prereq


- name: Install Python Pip3 Module
  shell: |
    python3 -m pip install --upgrade pip
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
  register: install_pip


- name: Install Python Pip Module for VMware Postgres Patroni
  shell: |
    pip3 install {{ item }}
  async: 180
  poll: 5
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
  register: install_pip3_python_modules
  with_items: "{{ common_pip3_module }}"


- name: Upgrade Python Pip3 Module Version
  shell: |
    pip3 install --upgrade pip
  async: 60
  poll: 5
  register: upgrade_pip
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"


- name: Install Python Pip3 Modules for VMware Postgres {{ pgsql.major_version }} Patroni on Workers
  shell: |
    pip3 install {{ item.pip3_name }}
  async: 60
  poll: 5
  register: install_pip3_python_modules_for_vmware_postgres_13_and_earlier_versions
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
  with_items: "{{ pg13_pip3_module }}"
  when: pgsql.major_version|int <= 13


- name: Install Python Pip3 Modules for Patroni in VMware Postgres {{ pgsql.major_version }} on Workers
  shell: |
    pip3 install {{ item.pip3_name }}
  async: 60
  poll: 5
  register: install_pip3_python_modules_for_vmware_postgres_14_and_higher_versions
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
  with_items: "{{ pg14_pip3_module }}"
  when: pgsql.major_version|int >= 14


- name: Install Prerequesties of Python Pip Modules for VMware Postgres Patroni
  shell: |
    pip3 install {{ item }}
  async: 60
  poll: 5
  register: install_pip3_python_etcd
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
  with_items: "{{ prereq_pip3_module }}"


- name: Install Python Pip3 modules for VMware Posgres Patroni
  shell: |
    pip3 install {{ item }}
  async: 60
  poll: 5
  register: install_pip3_patroni
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
  with_items: "{{ rh8_pip3_module }}"
  when: hostvars[inventory_hostname].ansible_distribution_major_version|int >= 8


