---
- name: Copy the VMware Postgres {{ pgsql.major_version }} RPM Package
  copy:
    src: "{{ item }}"
    dest: "{{ common.sudo_user_home_dir }}/{{ item }}"
    mode: 0644
    owner: "{{ common.sudo_user }}"
    group: "{{ common.sudo_group }}"
  register: copy_vmware_postgres
  with_items:
    - "{{ pgsql_pkg_name }}.{{ pgsql.arch_type }}.{{ pgsql.bin_type }}"


- name: Copy the VMware Postgres Patroni RPM Package
  copy:
    src: "{{ item }}"
    dest: "{{ common.sudo_user_home_dir }}/{{ item }}"
    mode: 0644
    owner: "{{ common.sudo_user }}"
    group: "{{ common.sudo_group }}"
  register: copy_patroni_rpm_package
  with_items:
    - "{{ patroni_pkg_name }}-{{ _patroni.build_version }}.{{ _patroni.os_version }}.{{ _patroni.arch_type }}.{{ _patroni.bin_type }}"
  when: _patroni.with_pkgs


- name: Install the VMware Postgres {{ pgsql.major_version }} RPM Package
  yum:
    name: "{{ common.sudo_user_home_dir }}/{{ item }}"
    state: present
    disable_gpg_check: yes
  async: 60
  poll: 5
  register: install_vmware_postgres_rpm_package
  with_items:
    - "{{ pgsql_pkg_name }}.{{ pgsql.arch_type }}.{{ pgsql.bin_type }}"


- name: Install the VMware Postgres Patroni RPM Package
  yum:
    name: "{{ pgsql.sudo_user_dir }}/{{ item }}"
    state: present
    disable_gpg_check: yes
  async: 60
  poll: 5
  register: install_paroni_rpm_package
  with_items:
    - "{{ patroni_pkg_name }}-{{ _patroni.build_version }}.{{ _patroni.os_version }}.{{ _patroni.arch_type }}.{{ _patroni.bin_type }}"
  when: _patroni.with_pkgs


