---
# Configure environments and variables
#
- name: Add line into /etc/locale.conf for LC_TYPE to prevent error
  lineinfile:
    path: /etc/locale.conf
    line: "LC_CTYPE=en_US.UTF-8"
  register: lctype_line_added

#
- name: Check if .bash_profile exits under {{ pgsql.base_dir }} directory
  become_user: postgres
  stat: path=/var/lib/pgsql/.bash_profile
  register: bash_profile_existed

#
- name: Sanity check for .bash_profile in {{ pgsql.base_dir }}
  become_user: postgres
  shell: "{{ item }}"
  with_items:
    - "touch {{ pgsql.base_dir }}/.bash_profile"
    - "chmod 600 {{ pgsql.base_dir }}/.bash_profile"
  register: bash_profile_checked
  when:
    - bash_profile_existed.stat.exists == False

#
- name: Insert Executable binary path into .bashrc for VMware Postgres {{ pgsql.major_version }}
  become_user: postgres
  lineinfile:
    path: "{{ pgsql.base_dir }}/.bash_profile"
    line: "export PATH={{ common.pgsql_bin_dir }}:$PATH"
  register: bin_path_inline_added
  when:
    - bash_profile_existed.stat.exists == True
    - hostvars[inventory_hostname].ansible_distribution_major_version|int == 7

