---
- name: Add Line into /etc/locale.conf for LC_TYPE to Prevent Error
  lineinfile:
    path: /etc/locale.conf
    line: "LC_CTYPE=en_US.UTF-8"
  register: add_lctype_line


- name: Check if .bash_profile exits under {{ pgsql.base_dir }} Directory
  become_user: postgres
  stat: path=/var/lib/pgsql/.bash_profile
  register: exists_bash_profile


- name: Sanity Check for .bash_profile in {{ pgsql.base_dir }}
  become_user: postgres
  shell: "{{ item }}"
  with_items:
    - "touch {{ pgsql.base_dir }}/.bash_profile"
    - "chmod 600 {{ pgsql.base_dir }}/.bash_profile"
  register: check_bash_profile
  when:
    - exists_bash_profile.stat.exists == False


- name: Insert Executable Binary Path into .bashrc for VMware Postgres {{ pgsql.major_version }}
  become_user: postgres
  lineinfile:
    path: "{{ pgsql.base_dir }}/.bash_profile"
    line: "export PATH={{ common.pgsql_bin_dir }}:$PATH"
  register: add_bin_path_inline
  when:
    - exists_bash_profile.stat.exists == True
    - hostvars[inventory_hostname].ansible_distribution_major_version|int == 7

