---
# Install Patroni Cluster for RHEL/CentOS/Rocky 7.x and 8.x
#
- name: Add line into /etc/locale.conf for LC_TYPE to prevent error
  lineinfile:
    path: /etc/locale.conf
    line: "LC_CTYPE=en_US.UTF-8"
  register: lctype_line_added

#
- name: Make sure we have a 'wheel' group
  group:
    name: wheel
    state: present
  register: wheel_group_added

#
- name: Allow 'wheel' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
  register: wheel_group_allowed

#
- name: Check if .bash_profile exits under /var/lib/pgsql directory
  become_user: postgres
  stat: path=/var/lib/pgsql/.bash_profile
  register: bash_profile_existed

#
- name: Sanity check for .bash_profile in /var/lib/pgsql
  become_user: postgres
  shell: "{{ item }}"
  with_items:
    - "touch {{ pgsql.base_dir }}/.bash_profile"
    - "chmod 600 {{ pgsql.base_dir }}/.bash_profile"
  register: bash_profile_checked
  when:
    - bash_profile_existed.stat.exists == False

#
- name: Insert executable binary path into .bashrc for VMware Postgres {{ pgsql.major_version }}
  become_user: postgres
  lineinfile:
    path: "{{ pgsql.base_dir }}/.bash_profile"
    line: "export PATH={{ common.pgsql_bin_dir }}:$PATH"
  register: bin_path_inline_added
  when:
    - bash_profile_existed.stat.exists == True
    - hostvars[inventory_hostname].ansible_distribution_major_version|int == 7
