#
- name: Create SSL Directory on {{ pgsql.base_dir }} directory for Primary worker node
  become_user: postgres
  shell: mkdir -p {{ ssl.ssl_dir }}
  register: create_ssl_dir
  when: inventory_hostname in groups['workers'][0]

#
- name: Generate a CA certificate private key on {{ pgsql.base_dir }}/certs directory for Primary worker node
  become_user: postgres
  shell: openssl genrsa -out {{ ssl.ssl_dir }}/ca.key 4096
  register: gen_ca_cert_priv_key
  when: inventory_hostname in groups['workers'][0]

#
- name: Generate the CA certificate on {{ pgsql.base_dir }}/certs directory for Primary worker node
  become_user: postgres
  shell: |
    openssl req -x509 -new -nodes -sha512 -days 3650 \
    -subj "/C={{ ssl.ssl_country }}/ST={{ ssl.ssl_state }}/L={{ ssl.ssl_location }}/O={{ ssl.ssl_organization }}/OU={{ ssl.ssl_organization_unit }}/CN={{ ssl.ssl_common_name }}/emailAddress={{ ssl.ssl_email }}" \
    -key {{ ssl.ssl_dir }}/ca.key \
    -out {{ ssl.ssl_dir }}/ca.crt
  register: gen_ca_cert
  when: inventory_hostname in groups['workers'][0]

#
- name: Generate a private key on {{ pgsql.base_dir }}/certs directory for Primary worker node
  become_user: postgres
  shell: openssl genrsa -out {{ ssl.ssl_dir }}/server.key 4096
  register: gen_priv_key
  when: inventory_hostname in groups['workers'][0]

#
- name: Generate a certificate signing request (CSR) on {{ pgsql.base_dir }}/certs directory for Primary worker node
  become_user: postgres
  shell: |
    openssl req -sha512 -new \
    -subj "/C={{ ssl.ssl_country }}/ST={{ ssl.ssl_state }}/L={{ ssl.ssl_location }}/O={{ ssl.ssl_organization }}/OU={{ ssl.ssl_organization_unit }}/CN={{ ssl.ssl_common_name }}/emailAddress={{ ssl.ssl_email }}" \
    -key {{ ssl.ssl_dir }}/server.key \
    -out {{ ssl.ssl_dir }}/server.csr
  register: gen_cert_sign_req
  when: inventory_hostname in groups['workers'][0]

#
- name: Copy an x509 v3 extension file on {{ pgsql.base_dir }}/certs directory for Promary worker node
  template: src=v3.ext.j2 dest={{ ssl.ssl_dir }}/v3.ext owner=postgres group=postgres mode=644 force=yes
  register: copy_x509_v3_ext
  when: inventory_hostname in groups['workers'][0]

#
- name: Replace the CRS and CRT file names on {{ pgsql.base_dir }}/certs directory for Primary worker node
  become_user: postgres
  shell: |
    openssl x509 -req -sha512 -days 3650 -extfile {{ ssl.ssl_dir }}/v3.ext \
    -CA {{ ssl.ssl_dir }}/ca.crt -CAkey {{ ssl.ssl_dir }}/ca.key -CAcreateserial \
    -in {{ ssl.ssl_dir }}/server.csr \
    -out {{ ssl.ssl_dir }}/server.crt
  register: replace_csr_crt
  when: inventory_hostname in groups['workers'][0]

#
- name: Synchronize ssl directory using rsync protocol on delegate host (push) for {{ pgsql.base_dir }}/certs directory in Primary worker node
  synchronize:
    src: "{{ ssl.ssl_dir }}"
    dest: "{{ pgsql.base_dir }}"
    mode: push
    recursive: yes
  delegate_to: "{{groups['workers'][0]}}"
  register: ssl_dir_synced
  when: inventory_hostname not in groups['workers'][0]

#
- name: Change permissions for cert files in {{ pgsql.base_dir }}/certs directory for all worker nodes
  file:
    path: "{{ ssl.ssl_dir }}/{{ item }}"
    state: file
    owner: postgres
    group: postgres
    mode: "0600"
  register: certs_permission_changed
  with_items:
    - "ca.crt"
    - "ca.key"
    - "ca.srl"
    - "server.crt"
    - "server.csr"
    - "server.key"
    - "v3.ext"

