---
- name: Run the patronictl Command-Line Utility to View the Cluster State with Patroni Started on All Worker Nodes
  become_user: postgres
  shell: |
    {{ _patroni.ctl_path }} -c /var/lib/pgsql/patroni.yml list
  register: list_patroni
  when: inventory_hostname in groups['control']


- name: Set Fact for Taking Leader Node
  set_fact:
    leader_node: "{{ ( list_patroni.stdout_lines | select('search', 'Leader') | list | string | split('|') )[1] | replace(' ', '') }}"
  delegate_to: "{{ item }}"
  delegate_facts: True
  with_items: "{{ groups['workers'] }}"
  when: inventory_hostname in groups['control']
# - debug: msg= "{{ leader_node }}"


- name: Create the Database Specified in Vars
  become_user: postgres
  vars:
    ansible_python_interpreter: /usr/bin/python3
  postgresql_db: name={{ pgsql.db_name }}
       template='template0'
       state=present
       login_unix_socket=/tmp
  register: create_database
  when: inventory_hostname == leader_node


- name: Ensure User has Access to the New Database
  become_user: postgres
  vars:
    ansible_python_interpreter: /usr/bin/python3
  postgresql_user: db={{ pgsql.db_name }}
       name={{ pgsql.db_user }}
       password={{ pgsql.db_password }}
       priv=ALL
       state=present
       login_unix_socket=/tmp
  register: create_user
  when: inventory_hostname == leader_node


- name: Ensure User does not have Unnecessary Permissions
  become_user: postgres
  vars:
    ansible_python_interpreter: /usr/bin/python3
  postgresql_user: name={{ pgsql.db_user }}
       role_attr_flags=SUPERUSER,CREATEDB,CREATEROLE,INHERIT,LOGIN,REPLICATION
       state=present
       login_unix_socket=/tmp
  register: enroll_permission
  when: inventory_hostname == leader_node
  # when: inventory_hostname in groups['workers'][0]
  # role_attr_flags=NOSUPERUSER,NOCREATEDB
  # role_attr_flags
  # [NO]SUPERUSER
  # [NO]CREATEROLE
  # [NO]CREATEDB
  # [NO]INHERIT
  # [NO]LOGIN
  # [NO]REPLICATION
  # [NO]BYPASSRLS
  # https://docs.ansible.com/ansible/2.8/modules/postgresql_user_module.html

