---
- name: Stop Services for VMware Postgres Patroni and ETCD
  systemd:
    name: "{{ item }}"
    state: stopped
    enabled: no
    daemon_reload: true
  register: stop_patroni_service
  ignore_errors: true
  until: stop_patroni_service is succeeded
  retries: 5
  delay: 20
  with_items:
    - etcd
    - patroni


#- name: Kill ETCD Process
#  shell: |
#    killall etcd
#  register: kill_etcd_processes
#  ignore_errors: true

