---

#
- name: Stop services for VMware Postgres Patroni and ETCD
  systemd:
    name: patroni
    enabled: no
    state: stopped
  register: patroni_etcd_service_stopped
  with_items:
    - etcd
    - patroni
  # until: patroni_etcd_service_stopped is succeeded
  # retries: 3
 
#
- name: Kill etcd process
  shell: ( killall etcd )
  register: etcd_processes_killed
  ignore_errors: yes
