---
- name: Unstall Patroni Pip3 Module
  become_user: root
  shell: |
    pip3 uninstall {{ item }} -y
  register: uninstall_pip3_patroni
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
  ignore_errors: true
  with_items: "{{ rh8_pip3_module }}"
  when: hostvars[inventory_hostname].ansible_distribution_major_version|int >= 8


- name: Uninstall Pip3 Modules for Higher Versions than VMware Postgres {{ pgsql.major_version }}
  shell: |
    pip3 uninstall {{ item.pip3_name }} -y
  register: uninstall_extra_pip3_modules_for_higher_than_vmware_postgres14
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
  ignore_errors: true
  with_items: "{{ pg14_pip3_module }}"
  when: pgsql.major_version|int >= 14


- name: Uninstall Pip3 Modules for Ealier Versions than VMware Postgres {{ pgsql.major_version }}
  shell: |
    pip3 uninstall {{ item.pip3_name }} -y
  register: uninstall_extra_pip3_modules_for_earlier_than_vmware_postgres13
  ignore_errors: true
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
  with_items: "{{ pg13_pip3_module }}"
  when: pgsql.major_version|int >= 13


- name: Uninstall Common Pip3 Modules ( typing/etcd and so on )
  shell: |
    pip3 uninstall {{ item }} -y
  register: uninstall_common_pip3_modules
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
  ignore_errors: true
  with_items: "{{ prereq_pip3_module }}"


