---
- name: Delete Variables and Configuration Files for Patroni and ETCD Systemd Unit
  file:
    path: "{{ item }}"
    state: absent
  register: delete_patroni_config_files
  ignore_errors: true
  with_items:
    - "/var/lib/pgsql/patroni.yml"
    - "/etc/systemd/system/patroni.service"
    - "/var/lib/pgsql/postgresql0.yml"
    - "/var/lib/pgsql/patroni_member.log"
    - "/var/lib/pgsql/etcd.yml"
    - "/var/lib/pgsql/etcd_logfile"
    - "/var/lib/pgsql/.bash_profile"
    - "/etc/etcd/etcd.conf"
    - "/usr/bin/etcd"
    - "/usr/bin/etcdctl"


- name: Delete Data Directories
  file:
    path: "/var/lib/pgsql/{{ item }}"
    state: absent
  register: delete_data_directories
  ignore_errors: true
  with_items:
    - "backups"
    - "data"
    - "patroni_data"
    - "wal_archive"
    - "pgpass0"
    - "requirements.txt"

