---
# Install Patroni Cluster for RHEL/CentOS/Rocky 7.x and 8.x
#
- name: Copy the VMware Postgres {{ major_version }} rpm package file to all nodes in workers
  copy:
    src: "{{ item }}"
    dest: "/home/jomoon/{{ item }}"
    mode: 0644
    owner: jomoon
    group: jomoon
  register: vmware_postgres_copied
  with_items:
    - "{{ package_name }}-{{ major_version }}.{{ minor_version }}-{{ patch_version }}.{{ rhel_version }}.x86_64.rpm"

#
- name: Copy ETCD {{ etcd_version }} rpm package for RHEL or Rocky 8 to all nodes in workers group
  copy:
    src: "{{ item }}"
    dest: "/home/jomoon/{{ item }}"
    mode: 0644
    owner: jomoon
    group: jomoon
  register: etcd_rpm_package_copied
  with_items:
    - "etcd-{{ etcd_version }}.{{ etcd_rhel_version }}.x86_64.rpm"
  when: hostvars[inventory_hostname].ansible_distribution_major_version|int <= 8


#
#- name: Build etcd of github.com
#  become: true
#  become_user: root
#  shell: |
#    cd /root; git clone https://github.com/coreos/etcd.git
#    cd /root/etcd; git fetch
#    cd /root/etcd; git checkout v3.4.28
#    cd /root/etcd; ./build
#    cp /root/etcd/bin/etcd /usr/bin/
#    cp /root/etcd/bin/etcdctl /usr/bin/
#  register: etcd_build
#  when: hostvars[inventory_hostname].ansible_distribution_major_version|int >= 8

#
- name: Download and configure etcd binary
  become: true
  become_user: root
  import_tasks: install-etcd-bin.yml
  when: hostvars[inventory_hostname].ansible_distribution_major_version|int >= 9

#
- name: Copy the patroni rpm file to all hosts in cluster
  copy:
    src: "{{ item }}"
    dest: "/home/jomoon/{{ item }}"
    mode: 0644
    owner: jomoon
    group: jomoon
  register: patroni_rpm_package_copied
  with_items:
    - "{{ package_name }}-patroni-{{ patroni_version }}.{{ rhel_version }}.x86_64.rpm"
  when: with_patroni_pkg

# - python-psycopg2
# - etcd
# - python34
# - python34-libs
# - python34-setuptools
# - python36-PyYAML
# - python36-pathspec

#
- name: Install VMware Postgres RPM Package on all hosts as root
  become: true
  yum:
    name: "/home/jomoon/{{ item }}"
    state: present
    disable_gpg_check: yes
  async: 60
  poll: 5
  register: vmware_postgres_rpm_package_installed
  with_items:
    - "{{ package_name }}-{{ major_version }}.{{ minor_version }}-{{ patch_version }}.{{ rhel_version }}.x86_64.rpm"

#
- name: Install Patroni RPM Package in VMware Postgres on all hosts as root
  become: true
  yum:
    name: "/home/jomoon/{{ item }}"
    state: present
    disable_gpg_check: yes
  async: 60
  poll: 5
  register: paroni_rpm_package_installed
  with_items:
    - "{{ package_name }}-patroni-{{ patroni_version }}.{{ rhel_version }}.x86_64.rpm"
  when: with_patroni_pkg

#
- name: Install ETCD rpm package on all nodes in workers group for RHEL or Rocky {{  hostvars[inventory_hostname].ansible_distribution_major_version }}
  become: true
  yum:
    name: "/home/jomoon/{{ item }}"
    state: present
    disable_gpg_check: yes
  async: 60
  poll: 5
  register: etcd_rpm_packages_installed
  with_items:
    - "etcd-{{ etcd_version }}.{{ etcd_rhel_version }}.x86_64.rpm"
  when: hostvars[inventory_hostname].ansible_distribution_major_version|int <= 8

#
- name: Install the etcd and Patroni prerequisites on all three nodes for CentOS 7
  become: true
  yum:
    name: "{{ item }}"
    state: present
    skip_broken: yes
  async: 180
  poll: 5
  register: etcd_prereq_rpm_packages_installed
  with_items:
    - python-psycopg2
    - etcd
  when:
    - hostvars[inventory_hostname].ansible_distribution_major_version|int == 7
    - install_dep_pkgs
#
