---
# Install VMWare Postgres for Red Hat / CentOS

# for now fail if it's not a Red Hat based system
- name: Check OS ( GPDB )
  fail: msg="Not a Red Hat based system!"
  when: ansible_os_family != 'RedHat'

#
- name: x
  import_tasks: config-firewall.yml
  tags: install
  when: config_firewall == true

#
- name: x
  import_tasks: install-dep-pkgs.yml
  tags: install
  when: install_dep_pkgs == true

#
- name: Install rpm and python packages for patroni of vmware-postgres in Red Hat / CentOS / Rocky Linux
  import_tasks: install-pkgs.yml
  tags: install
  when: install_pkgs == true

#
- name: x
  import_tasks: install-pip-module.yml
  tags: install
  when: install_pip_module == true


#
- name: x
  import_tasks: config-env.yml
  tags: install
  when: config_env == true

#
- name: Enable SSL for patroni of vmware-postgres in Red Hat / CentOS / Rocky Linux
  import_tasks: enable-ssl.yml
  tags: install
  when: enable_ssl == true

#
- name: Configure patroni of vmware-postgres in Red Hat / CentOS / Rocky Linux
  import_tasks: config-patroni.yml
  tags: install
  when: config_patroni == true

#
- name: Add users for vmware-postgres patroni cluster in Red Hat / CentOS / Rocky Linux
  import_tasks: add-users.yml
  tags: install
  when: add_users == true

#
- name: Uninstallation of vmware postgres for Red Hat / CentOS
  import_tasks: uninstall.yml
  tags: uninstall

#
- name: Upgrade of vmware postgres for Red Hat / CentOS
  import_tasks: upgrade.yml
  tags: upgrade
