---
# Install VMWare Postgres for Red Hat / CentOS

# for now fail if it's not a Red Hat based system
- name: Check OS ( GPDB )
  fail: msg="Not a Red Hat based system!"
  when: ansible_os_family != 'RedHat'

- name: Install rpm and python packages for patroni of vmware-postgres in Red Hat / CentOS / Rocky Linux
  include: install-pkgs.yml
  tags: install
  when: install_pkgs == true

- name: Enable SSL for patroni of vmware-postgres in Red Hat / CentOS / Rocky Linux
  include: enable-ssl.yml
  tags: install
  when: enable_ssl == true

- name: Configure patroni of vmware-postgres in Red Hat / CentOS / Rocky Linux
  include: configure.yml
  tags: install
  when: configure_patroni == true

#
- name: Uninstallation of vmware postgres for Red Hat / CentOS
  include: uninstall.yml
  tags: uninstall

#
- name: Upgrade of vmware postgres for Red Hat / CentOS
  include: upgrade.yml
  tags: upgrade

