---
# Uninstall Patroni Cluster for RHEL/CentOS/Rocky 7.x and 8.x
#
- name: Stop services for patroni and etcd
  become: true
  systemd:
    name: patroni
    enabled: no
    state: stopped
  register: patroni_etcd_service_stopped
  with_items:
    - patroni
    - etcd
  ignore_errors: yes

#
- name: Kill etcd process
  become: true
  become_user: postgres
  shell: ( killall etcd )
  async: 60
  poll: 5
  register: etcd_processes_killed
  ignore_errors: yes

#
- name: Uninstall pip modules of Patroni prerequisites on all three nodes
  become: true
  become_user: root
  shell: ( export PATH=$PATH:/usr/local/bin && pip3 uninstall -r /var/lib/pgsql/requirements.txt -y )
  async: 120
  poll: 5
  register: pip_prereq_modules_uninstalled
  ignore_errors: yes
  when: uninstall_python_module

#
- name: Delete configuration files for patroni and systemd
  become: true
  file:
    path: "{{ item }}"
    state: absent
  register: patroni_config_files_deleted
  with_items:
    - "/var/lib/pgsql/patroni.yml"
    - "/etc/systemd/system/patroni.service"
    - "/var/lib/pgsql/postgresql0.yml"
    - "/var/lib/pgsql/patroni_member.log"
    - "/var/lib/pgsql/etcd.yml"
    - "/var/lib/pgsql/etcd_logfile"
    - "/var/lib/pgsql/.bash_profile"

#
- name: Delete data directories
  become: true
  file:
    path: "/var/lib/pgsql/{{ item }}"
    state: absent
  register: data_directories_deleted
  with_items:
    - "backups"
    - "data"
    - "patroni_data"
    - "wal_archive"
    - "pgpass0"
    - "requirements.txt"

#
- name: Delete old patroni data directory for patroni cluster
  become: true
  shell: rm -rf /var/lib/pgsql/.local /var/lib/pgsql/.cache /var/lib/pgsql/patroni_data_*
  register: backup_hidden_data_directories_deleted

#
- name: Uninstall pip3 modules for higher versions than vmware-postgres {{ major_version }}
  become: true
  become_user: root
  shell: ( export PATH=$PATH:/usr/local/bin && pip3 uninstall {{ item }} -y )
  async: 120
  poll: 5
  register: extra_pip3_modules_for_higher_than_vmware_postgres_14_uninstalled
  ignore_errors: yes
  with_items:
    - "pyopenssl"
    - "pyrsistent"
  when:
    - uninstall_python_module
    - major_version >= 14

#
- name: Uninstall pip3 modules for ealier versions than vmware-postgres {{ major_version }}
  become: true
  become_user: root
  shell: ( export PATH=$PATH:/usr/local/bin && pip3 uninstall {{ item }} -y )
  async: 120
  poll: 5
  register: extra_pip3_modules_for_earlier_than_vmware_postgres_13_uninstalled
  ignore_errors: yes
  with_items:
    - "psycopg2-binary"
  when:
    - uninstall_python_module
    - major_version >= 13

#
- name: Uninstall common pip3 modules ( typing/etcd and so on )
  become: true
  become_user: root
  shell: ( export PATH=$PATH:/usr/local/bin && pip3 uninstall {{ item }} -y )
  async: 120
  poll: 5
  register: common_pip3_modules_uninstalled
  ignore_errors: yes
  with_items:
    - "etcd"
    - "etcd3"
    - "python-etcd"
    - "typing"
    - "ydiff"
    - "psutil"
    - "prettytable"
    - "click"
    - "setuptools-rust"
    - "wheel"
    - "pip"
  when:
    - uninstall_python_module

#
- name: Delete the dependencies file of etcd
  become: true
  become_user: postgres
  file:
    path: /var/lib/pgsql/requirements.txt
    state: absent
  register: patroni_prereq_uninstalled_of_etcd_deleted
  ignore_errors: yes
  when: uninstall_python_module

#
- name: Uninstall RPM packages of the etcd and Patroni prerequisites
  become: true
  yum:
    name: "{{ item }}"
    state: absent
    skip_broken: yes
  async: 120
  poll: 5
  register: prereq_rpm_packages_of_patroni_deleted
  ignore_errors: yes
  with_items:
    - "python3"
    - "python3-rpm-generators"
    - "python3-devel"
    - "gcc"
    - "etcd"
    - "python-psycopg2"
    - "python3-pip"
    - "python3-setuptools"
    - "python27-python-setuptools"
    - "yamllint"
    - "daemonize"
  when: remove_dep_packages
  #  - python34-setuptools

#
- name: Uninstall VMware Postgres RPM packages
  become: true
  yum:
    name: "{{ item }}"
    state: absent
  async: 120
  poll: 5
  register: vmware_postgres_rpm_packages_deleted
  with_items:
    - "{{ package_name }}-{{ major_version }}.{{ minor_version }}-{{ patch_version }}.{{ rhel_version }}"
    - "vmware-postgres"

#
- name: Uninstall Patroni RPM Package VMware Postgres RPM packages
  become: true
  yum:
    name: "{{ item }}"
    state: absent
  async: 120
  poll: 5
  register: patroni_rpm_packages_uninstalled
  with_items:
    - "{{ package_name }}-patroni-{{ patroni_version }}"
  when: with_patroni_pkg

#
- name: Delete the vmwawre-postgres rpm file
  become: true
  file:
    path: /home/jomoon/{{ package_name }}-{{ major_version }}.{{ minor_version }}-{{ patch_version }}.{{ rhel_version }}.x86_64.rpm
    state: absent
  register: vmware_postgres_rpm_packages_deleted

#
- name: Delete the vmwawre-postgres{{ major_version }}-paroni rpm file
  become: true
  file:
    path: "/home/jomoon/{{ package_name }}-patroni-{{ patroni_version }}.{{ rhel_version }}.x86_64.rpm"
    state: absent
  register: patroni_rpm_packages_deleted
  when: with_patroni_pkg

#
- name: List iptables rules
  become: true
  become_user: root
  shell: ( iptables -nL )
  register: iptables_rules_listed

#
- name: Flush iptables rules
  become: true
  become_user: root
  shell: ( iptables -F )
  register: iptables_rules_flushed

#
- name: Stop and disable firewalld
  become: true
  systemd:
    name: firewalld
    state: stopped
    enabled: false
  register: firewalld_service_stopped

- debug: msg={{ iptables_rules_listed.stdout }}
  tags:
    - print_debug
