#
- name: Verify the state of worker's instances
  become_user: postgres
  shell: ( source /var/lib/pgsql/.bash_profile ; {{ common.pgsql_bin_dir }}/pg_autoctl show state )
  register: workers_instance_state_verified
  args:
    chdir: "/var/lib/pgsql"
    executable: /bin/bash
  when: inventory_hostname in groups['workers']

#
- debug: msg={{ workers_instance_state_verified }}
  become_user: postgres
  tags: print_debug
  when: inventory_hostname in groups['workers']
