---
- name: Verify the State of Worker Instances
  become_user: postgres
  shell: |
    source /var/lib/pgsql/.bash_profile
    {{ common.pgsql_bin_dir }}/pg_autoctl show state
  register: verify_workers_instance_state
  args:
    chdir: "/var/lib/pgsql"
    executable: /bin/bash
  when: inventory_hostname in groups['workers']


- debug: msg={{ verify_workers_instance_state }}
  become_user: postgres
  tags: print_debug
  when: inventory_hostname in groups['workers']

