# Create instance for worker nodes
#
- name: Insert executable binary path into .bashrc for VMware Postgres {{ pgsql.major_version }}
  become_user: postgres
  lineinfile:
    path: "{{ item }}"
    line: "export PATH={{ common.pgsql_bin_dir }}:$PATH"
  with_items:
    - "{{ pgsql.base_dir }}/.bash_profile"
    - "{{ pgsql.home_dir }}/.bashrc"

#
- name: Create workers instance. It will automatically be set by the monitor as the primary node with read-write capability (PGDATA = /var/lib/pgpsql/ha)
  become_user: postgres
  shell: ( source {{ pgsql.base_dir }}/.bash_profile ; {{ common.pgsql_bin_dir }}/pg_autoctl create postgres --pgdata '{{ pgsql.base_dir }}/{{ pgfailover.workers_database }}' --auth trust --ssl-self-signed --username ha-admin --dbname '{{ pgfailover.app_database }}' --hostname '{{ inventory_hostname }}' --pgctl {{ common.pgsql_bin_dir }}/pg_ctl --monitor "postgres://autoctl_node@{{ hostvars[groups['monitor'][0]].ansible_hostname }}/pg_auto_failover?sslmode={{ pgfailover.sslmode }}" )
  async: 300
  poll: 5
  register: workers_instance_created
  args:
    chdir: "{{ pgsql.base_dir }}"
    executable: /bin/bash

#
- name: Create systemd service file of worker instances
  become_user: postgres
  shell: ( source {{ pgsql.base_dir }}/.bash_profile ; {{ common.pgsql_bin_dir }}/pg_autoctl -q show systemd --pgdata '{{ pgsql.base_dir }}/{{ pgfailover.workers_database }}' > pgautofailover.service )
  register: workers_systemd_service_added
  async: 180
  poll: 5
  args:
    chdir: "{{ pgsql.base_dir }}"
    executable: /bin/bash

#
- name: Copy primary systemd service file of worker instances
  copy:
    src: "{{ pgsql.base_dir }}/pgautofailover.service"
    dest: "/etc/systemd/system/"
    owner: root
    group: root
    mode: 0644
    remote_src: true

#
- name: Replace database directory for worker instacnes
  become_user: postgres
  replace:
    path: "{{ pgsql.base_dir }}/.bash_profile"
    regexp: '^(.*)PGDATA=(.*)$'
    replace: 'PGDATA=/{{ pgsql.base_dir }}/{{ pgfailover.workers_database }}'
    backup: yes

#
- name: Reload and start primary systemd service of worker instances
  systemd:
    name: pgautofailover
    state: started
    daemon_reload: yes
  register: pgautofailover_service_added
  async: 60
  poll: 5

