---
- name: Stop and Disable Firewalld
  service:
    name: firewalld
    state: stopped
    enabled: false


- name: Flush IPTables Rules
  shell: ( iptables -F )
  register: iptables_rules_flushed


- name: List IPTables Rules
  shell: ( iptables -nL )
  register: iptables_rules_listed


- debug: msg={{ iptables_rules_listed.stdout }}
  tags: print_debug

