#
- name: Create SSL Directory on {{ pgsql.base_dir }} diretory
  become_user: postgres
  shell: mkdir {{ ssl.ssl_dir }}
  register: create_ssl_dir
  when: inventory_hostname in groups['monitor']


- name: Generate a CA Certificate Private Key on "{{ pgsql.base_dir }}/{{ ssl.ssl_dir }}" Diretory
  become_user: postgres
  shell: openssl genrsa -out {{ ssl.ssl_dir }}/ca.key 4096
  register: gen_ca_cert_priv_key
  when: inventory_hostname in groups['monitor']


- name: Generate the CA Certificate on "{{ pgsql.base_dir }}/{{ ssl.ssl_dir }}" Diretory
  become: true
  become_user: postgres
  shell: |
    openssl req -x509 -new -nodes -sha512 -days 3650 \
    -subj "/C={{ ssl.ssl_country }}/ST={{ ssl.ssl_state }}/L={{ ssl.ssl_location }}/O={{ ssl.ssl_organization }}/OU={{ ssl.ssl_organization_unit }}/CN={{ ssl.ssl_common_name }}/emailAddress={{ ssl.ssl_email }}" \
    -key {{ ssl.ssl_dir }}/ca.key \
    -out {{ ssl.ssl_dir }}/ca.crt
  register: gen_ca_cert
  when: inventory_hostname in groups['monitor']


- name: Generate a Private Key on "{{ pgsql.base_dir }}/{{ ssl.ssl_dir }}" Diretory
  become_user: postgres
  shell: openssl genrsa -out {{ ssl.ssl_dir }}/server.key 4096
  register: gen_priv_key
  when: inventory_hostname in groups['monitor']


- name: Generate a Certificate Signing Request (CSR) on "{{ pgsql.base_dir }}/{{ ssl.ssl_dir }}" Diretory
  become_user: postgres
  shell: |
    openssl req -sha512 -new \
    -subj "/C={{ ssl.ssl_country }}/ST={{ ssl.ssl_state }}/L={{ ssl.ssl_location }}/O={{ ssl.ssl_organization }}/OU={{ ssl.ssl_organization_unit }}/CN={{ ssl.ssl_common_name }}/emailAddress={{ ssl.ssl_email }}" \
    -key {{ ssl.ssl_dir }}/server.key \
    -out {{ ssl.ssl_dir }}/server.csr
  register: gen_cert_sign_req
  when: inventory_hostname in groups['monitor']


- name: Copy an x509 v3 Extension File onto "{{ pgsql.base_dir }}/{{ ssl.ssl_dir }}" Diretory
  template: src=v3.ext.j2 dest={{ ssl.ssl_dir }}/v3.ext owner=postgres group=postgres mode=644 force=yes
  register: copy_x509_v3_ext
  when: inventory_hostname in groups['monitor']


- name: Replace the CRS and CRT File Names on "{{ pgsql.base_dir }}/{{ ssl.ssl_dir }}" Diretory for Monitor Node
  become_user: postgres
  shell: |
    openssl x509 -req -sha512 -days 3650 -extfile {{ ssl.ssl_dir }}/v3.ext \
    -CA {{ ssl.ssl_dir }}/ca.crt -CAkey {{ ssl.ssl_dir }}/ca.key -CAcreateserial \
    -in {{ ssl.ssl_dir }}/server.csr \
    -out {{ ssl.ssl_dir }}/server.crt
  register: replace_csr_crt
  when: inventory_hostname in groups['monitor']


- name: Disable SSL on Monitor
  become_user: postgres
  shell: |
    export PGDATA=/var/lib/pgsql/monitor && {{ common.pgsql_bin_dir }}/pg_autoctl disable ssl
  register: disable_ssl_monitor
  when: inventory_hostname in groups['monitor']


- name: Disable SSL on Workers
  become_user: postgres
  shell: |
    export PGDATA=/var/lib/pgsql/ha && {{ common.pgsql_bin_dir }}/pg_autoctl disable ssl
  register: enable_ssl_workers
  when: inventory_hostname in groups['workers']


- name: Restart PGAutoFailover Service to Apply SSL Changes
  become_user: postgres
  shell: |
    sudo systemctl restart pgautofailover
  register: pgautofailover_restarted
  when: inventory_hostname in groups['monitor'] or inventory_hostname in groups['workers']


- name: Enable SSL on Monitor
  become_user: postgres
  shell: |
    source /var/lib/pgsql/.bash_profile ; {{ common.pgsql_bin_dir }}/pg_autoctl enable ssl --pgdata {{ pgsql.base_dir }}/monitor \
    --ssl-ca-file '' --ssl-crl-file '' \
    --server-key {{ ssl.ssl_dir }}/server.key --server-cert {{ ssl.ssl_dir }}/server.crt --ssl-mode prefer
  register: enable_ssl_monitor
  when: inventory_hostname in groups['monitor']


- name: Synchronize "{{ pgsql.base_dir }}/{{ ssl.ssl_dir }}" Diretory Using Rsync Protocol on Delegate Host ( Push )
  synchronize:
    src: "{{ ssl.ssl_dir }}"
    dest: "{{ pgsql.base_dir }}"
    mode: push
    recursive: yes
  delegate_to: "{{groups['monitor'][0]}}"
  register: ssl_dir_synced
  when: inventory_hostname in groups['workers']


- name: Change Permissions for Cert Files on "{{ pgsql.base_dir }}/{{ ssl.ssl_dir }}" Diretory
  file:
    path: "{{ ssl.ssl_dir }}/{{ item }}"
    state: file
    owner: postgres
    group: postgres
    mode: "0600"
  register: certs_permission_changed
  with_items:
    - ca.key
    - server.csr
    - server.key
    - ca.crt
    - server.crt
  when: inventory_hostname in groups['workers']
  #  - root.crl


- name: Enable SSL on Workers
  become_user: postgres
  shell: |
    source /var/lib/pgsql/.bash_profile ; {{ common.pgsql_bin_dir }}/pg_autoctl enable ssl --pgdata {{ pgsql.base_dir }}/ha \
    --ssl-ca-file '' --ssl-crl-file '' \
    --server-key {{ ssl.ssl_dir }}/server.key --server-cert {{ ssl.ssl_dir }}/server.crt --ssl-mode prefer
  register: enable_ssl_workers
  when: inventory_hostname in groups['workers']


- name: Restart PGAutoFailover to Apply Changes of SSL Config
  become: true
  shell: |
    sudo systemctl restart pgautofailover
  register: pgautofailover_restarted
  when: inventory_hostname in groups['monitor'] or inventory_hostname in groups['workers']

