---
- name: Check OS ( PGAutoFailover )
  fail: msg="Not a Red Hat based system!"
  when: ansible_os_family != 'RedHat' or ansible_os_family != 'CentOS' or  ansible_os_family != 'Rocky'


- name: Set Facts for Package Name and List and Network Range
  import_tasks: set-facts.yml
  tags:
    - install
    - uninstall


- name: Stop and Diable Firewalld
  import_tasks: disable-firewall.yml
  when: disable_firwall == true


- name: Install Common Requirements
  import_tasks: install-pgsql-pkgs.yml
  tags: install
  when: install_dep_pkgs == true


- name: Install Monitor Instances
  import_tasks: deploy-monitor.yml
  tags: install
  when: deploy_monitor == true and inventory_hostname in groups['monitor']


- name: Install Primary Worker Instances
  import_tasks: deploy-workers.yml
  tags: install
  when: deploy_workers == true and ( inventory_hostname in groups['workers'] and inventory_hostname in groups['primary'] )


- name: Install Secondary Worker Instances
  import_tasks: deploy-workers.yml
  tags: install
  when: deploy_workers == true and ( inventory_hostname in groups['workers'] and inventory_hostname in groups['secondary'] )


- name: Check the Status of PGAutoFailover
  import_tasks: check-status-workers.yml
  tags: install


- name: Create Database and Users
  import_tasks: add-users.yml
  tags: install
  when: add_users == true


- name: Enable SSL on Monitor
  import_tasks: enable-ssl-monitor.yml
  tags: install
  when: enable_ssl == true


- name: Uninstall PGAutoFailover
  import_tasks: uninstall.yml
  tags: uninstall


- name: Upgrade PGAutoFailover
  import_tasks: upgrade.yml
  tags: upgrade

