#
- name: Copy ca.conf
  become: true
  become_user: postgres
  template: src=ca.conf.j2 dest={{ pgsql_ssl_dir }}/ca.conf owner=postgres group=postgres mode=644 force=yes
  register: ca_conf_copied
  when: inventory_hostname in groups['monitor']

# Test for Client
- name: xx01
  become: true
  become_user: postgres
  shell: |
    touch {{ pgsql_ssl_dir }}/certindex
    echo 01 > {{ pgsql_ssl_dir }}/certserial
    echo 01 > {{ pgsql_ssl_dir }}/crlnumber
  register: xx01
  when: inventory_hostname in groups['monitor']

# Test for Client
- name: xx00
  become: true
  become_user: postgres
  shell: |
    openssl ca -batch -config {{ pgsql_ssl_dir }}/ca.conf -notext -in {{ pgsql_ssl_dir }}/server.csr -out {{ pgsql_ssl_dir }}/server.crt
  register: xx00
  when: inventory_hostname in groups['monitor']

# Test for Client
- name: xx02
  become: true
  become_user: postgres
  shell: |
    openssl pkcs12 -export -out {{ pgsql_ssl_dir }}/server.p12 -inkey {{ pgsql_ssl_dir }}/server.key -in {{ pgsql_ssl_dir }}/server.crt -chain -CAfile {{ pgsql_ssl_dir }}/ca.crt -passout pass: -passin pass:""
  register: xx02
  when: inventory_hostname in groups['monitor']

# Test for Client
- name: xx03
  become: true
  become_user: postgres
  shell: openssl ca -config {{ pgsql_ssl_dir }}/ca.conf -gencrl -keyfile {{ pgsql_ssl_dir }}/ca.key -cert {{ pgsql_ssl_dir }}/ca.crt -out {{ pgsql_ssl_dir }}/root.crl.pem
  register: xx03
  when: inventory_hostname in groups['monitor']

# Test for Client
- name: xx04
  become: true
  become_user: postgres
  shell: |
    openssl crl -inform PEM -in {{ pgsql_ssl_dir }}/root.crl.pem -outform DER -out {{ pgsql_ssl_dir }}/root.crl
    rm {{ pgsql_ssl_dir }}/root.crl.pem
  register: xx04
  when: inventory_hostname in groups['monitor']


# Test for Client
- name: xx05
  become: true
  become_user: postgres
  shell: |
    openssl ca -config {{ pgsql_ssl_dir }}/ca.conf -revoke {{ pgsql_ssl_dir }}/server.crt -keyfile {{ pgsql_ssl_dir }}/ca.key -cert {{ pgsql_ssl_dir }}/ca.crt
  register: xx05
  when: inventory_hostname in groups['monitor']

#
- name: Synchronize ssl directory using rsync protocol on delegate host (push)
  synchronize:
    src: "{{ pgsql_ssl_dir }}"
    dest: "{{ pgsql_base_dir }}"
    mode: push
    recursive: yes
  delegate_to: "{{groups['monitor'][0]}}"
  register: ssl_dir_synced
  when: inventory_hostname in groups['workers']

#
- name: Change permissions for cert files
  become: true
  file:
    path: "{{ pgsql_ssl_dir }}/{{ item }}"
    state: file
    owner: postgres
    group: postgres
    mode: "0600"
  register: certs_permission_changed
  with_items:
    - 01.pem
    - ca.key
    - certindex.attr
    - certserial
    - crlnumber.old
    - server.csr
    - v3.ext
    - ca.conf
    - ca.srl
    - certindex.attr.old
    - certserial.old
    - root.crl
    - server.key
    - ca.crt
    - certindex
    - certindex.old
    - crlnumber
    - server.crt
    - server.p12
