#
- name: Stop systemd service of workers instance
  become: true
  systemd:
    name: pgautofailover
    state: stopped
    daemon_reload: yes
  register: pgautofailover_service_stopped
  async: 60
  poll: 5
  ignore_errors: yes

#
- name: Delete configuration files and data directory for pgautofailover
  become: true
  file:
    path: "{{ item }}"
    state: absent
  register: patroni_config_files_deleted
  with_items:
    - "/var/lib/pgsql/{{ monitor_database }}"
    - "/var/lib/pgsql/{{ workers_database }}"
    - "/var/lib/pgsql/{{ app_database }}"
    - "/var/lib/pgsql/data"
    - "/var/lib/pgsql/backup"
    - "/var/lib/pgsql/backups"
    - "/var/lib/pgsql/pgautofailover.service"
    - "/var/lib/pgsql/.bash_profile"
    - "/var/lib/pgsql"

#
- name: Uninstall Python3 Packages
  become: true
  yum:
    name: "{{ item }}"
    state: absent
    skip_broken: yes
  async: 120
  poll: 5
  with_items:
    - python3-utils
    - python3-PyYAML
    - daemonize
    - python3-pathspec
    - python3-rpm-generators
  when: remove_dep_packages and hostvars[inventory_hostname].ansible_distribution_major_version|int >= 8

#
- name: Uninstall Python3 Packages
  become: true
  yum:
    name: "{{ item }}"
    state: absent
    skip_broken: yes
  async: 120
  poll: 5
  with_items:
    - python3
    - python3-devel
    - python3-pip
    - python3-setuptools
    - yamllint
    - gcc
    - epel-release
  when: remove_dep_packages
  #  - python3-libs

#
- name: Delete "{{ user }}" User
  user:
    name: "{{ user }}"
    state: absent

#
- name: Delete "{{ group }}" Group
  group:
    name: "{{ group }}"
    state: absent

#
#- name: Disallow 'wheel' group to have passwordless sudo
#  become: true
#  lineinfile:
#    dest: /etc/sudoers
#    state: absent
#    regexp: '^%wheel'
#    line: '^#%wheel ALL=(ALL) NOPASSWD: ALL'
#    validate: 'visudo -cf %s'

#
#- name: Make sure we have a 'wheel' group
#  become: true
#  group:
#    name: wheel
#    state: present

#
- name: Uninstall VMware Postgres rpm package
  become: true
  become_user: root
  yum:
    name: "{{ package_name }}-{{ major_version }}.{{ minor_version }}-{{ patch_version }}.{{ rhel_version }}.x86_64"
    state: absent
    disable_gpg_check: true
  async: 180
  poll: 5

#
- name: Delete vmwawre-postgres rpm package file
  become: true
  file:
    path: /home/jomoon/{{ package_name }}-{{ major_version }}.{{ minor_version }}-{{ patch_version }}.{{ rhel_version }}.x86_64.rpm
    state: absent

#
- name: Stop and disable firewalld
  become: true
  service:
    name: firewalld
    state: stopped
    enabled: false

#
- name: Reload systemd daemon
  become: true
  systemd:
    daemon_reload: yes
  register: sysemd_daemon_reloaded
  async: 60
  poll: 5


#
- name: Flush iptables rules
  become: true
  shell: ( iptables -F )
  register: iptables_rules_flushed

#
- name: List iptables rules
  become: true
  shell: ( iptables -nL )
  register: iptables_rules_listed

#
- debug: msg={{ iptables_rules_listed.stdout }}
  tags:
    - print_debug
