---
- name: Uninstall VMware Postgres RPM Package
  package:
    name: "{{ common.pgsql_pkg_name }}"
    state: absent
    disable_gpg_check: true
  register: uninstall_pkgs
  async: 180
  poll: 5
  vars:
    ansible_python_interpreter: "{{ yum_python_version }}"


- name: Delete VMware Postgres RPM File
  file:
    path: "{{ common.sudo_user_home_dir }}/{{ pgsql_pkg_name }}.{{ pgsql.arch_type }}.{{ pgsql.bin_type }}"
    state: absent
  register: delete_pkgs


- name: Delete Configuration Files and Data Directory for VMware Postgres PGAutoFailover
  file:
    path: "{{ item }}"
    state: absent
  register: delete_patroni_config_files
  with_items: "{{ delete_file_list }}"


- name: Uninstall Prerequesties RPM Packages for VMware Postgres PGAutoFailover
  package:
    name: "{{ rh_uninstall_pkgs }}"
    state: absent
    skip_broken: yes
  vars:
    ansible_python_interpreter: "{{ yum_python_version }}"

