#
# Destroy VMWare Postgres PGAutoFailover Cluster on {{ ansible_distribution }}
#
- set_fact:
    rh_uninstall_pkgs: "{{ remove_rh_common_dep_pkgs ~ ',' ~ rh7_dep_pkgs ~ ',' ~ rh7_python_pkgs }}"
  when: ( ansible_distribution == "RedHat" or ansible_distribution == "CentOS" or ansible_distribution == "Rocky" ) and ansible_distribution_major_version|int <= 7
- set_fact:
    rh_uninstall_pkgs: "{{ remove_rh_common_dep_pkgs ~ ',' ~ rh8_dep_pkgs ~ ',' ~ rh8_python_pkgs }}"
  when: ( ansible_distribution == "RedHat" or ansible_distribution == "CentOS" or ansible_distribution == "Rocky" ) and ansible_distribution_major_version|int == 8
- set_fact:
    rh_uninstall_pkgs: "{{ remove_rh_common_dep_pkgs ~ ',' ~ rh9_dep_pkgs ~ ',' ~ rh9_python_pkgs }}"
  when: ( ansible_distribution == "RedHat" or ansible_distribution == "CentOS" or ansible_distribution == "Rocky" ) and ansible_distribution_major_version|int >= 9

#
- name: Define package names for VMware Postgres
  set_fact:
    pgsql_pkg_name: "{{ common.pgsql_pkg_name }}-{{ pgsql.major_version }}.{{ pgsql.minor_version }}-{{ pgsql.patch_version }}.{{ pgsql.os_version }}.{{ pgsql.arch_type }}.{{ pgsql.bin_type }}"

#
- name: Stop systemd service of workers instance
  systemd:
    name: pgautofailover
    state: stopped
    daemon_reload: yes
  register: pgautofailover_service_stopped
  async: 60
  poll: 5
  ignore_errors: yes

#
- name: Alternative python version 2 for RHEL/CentOS 7.x
  shell: |
    /usr/sbin/update-alternatives --install /usr/bin/python python /usr/bin/python2 1
    /usr/sbin/alternatives --set python /usr/bin/python2
  register: alternatives_python2
  when:
    - hostvars[inventory_hostname].ansible_distribution_major_version|int <= 7
    - ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS' or ansible_distribution == 'Rocky'

#
- name: Uninstall VMware Postgres RPM package
  yum:
    name: "{{ common.pgsql_pkg_name }}"
    state: absent
    disable_gpg_check: true
  async: 180
  poll: 5

#
- name: Delete VMware Postgres RPM file
  file:
    path: "{{ common.sudo_user_home_dir }}/{{ pgsql_pkg_name }}.{{ pgsql.arch_type }}"
    state: absent

#
- name: Delete configuration files and data directory for pgautofailover
  file:
    path: "{{ item }}"
    state: absent
  register: patroni_config_files_deleted
  with_items: "{{ delete_file_list }}"

#
- name: Uninstall Prerequesties RPM Packages for VMware Postgres PGAutoFailover
  yum:
    name: "{{ rh_uninstall_pkgs }}"
    state: absent
    skip_broken: yes

#
- name: Reload systemd daemon
  systemd:
    daemon_reload: yes
  register: sysemd_daemon_reloaded
  async: 60
  poll: 5

#
- name: Stop and disable firewalld
  service:
    name: firewalld
    state: stopped
    enabled: false

#
- name: Flush iptables rules
  shell: ( iptables -F )
  register: iptables_rules_flushed

#
- name: List iptables rules
  shell: ( iptables -nL )
  register: iptables_rules_listed

#
- debug: msg={{ iptables_rules_listed.stdout }}
  tags: print_debug
