- name: Verify the state of Postgres instance
  become: true
  become_user: postgres
  shell: ( source /var/lib/pgsql/.bash_profile ; {{ bin_dir }}/pg_ctl -V )
  register: postgres_instance_state_verified
  args:
    chdir: "/var/lib/pgsql"
    executable: /bin/bash

- debug: msg={{ postgres_instance_state_verified }}
  become: true
  become_user: postgres
  tags:
    - print_debug
