---
- name: Copy InfluxDB Package Repo file
  template: src={{ item.src }} dest={{ item.dest }} owner=root group=root mode=644 force=yes
  register: copy_influxdb_repo_config
  with_items:
    - { src: "influxdata.repo.j2",   dest: "/etc/yum.repos.d/influxdata.repo" }


- name: Install Dependent and Grafana RPM Packages
  yum:
    name: "{{ item }}"
    state: present
    # skip_broken: yes
  async: 120
  poll: 5
  with_items:
    - epel-release
    - python3
    - python3-pip
    - postgresql-contrib
    - postgresql-devel
    - influxdb2
    - influxdb2-cli
    - grafana
    - grafana-pcp


- name: Install pip modules for grafana
  shell: |
    pip3 install setuptools_rust
    python3 -m pip install --upgrade pip
    pip3 install --upgrade setuptools_rust
    python3 -m pip install --upgrade Pillow
    pip3 install wheel
  async: 120
  poll: 5
  register: install_pip_module


- name: Copy the grafana ini file
  template: src={{ item.src }} dest={{ item.dest }} owner=root group=root mode=644 force=yes
  register: systemd_file_copied
  with_items:
    - { src: "grafana.ini.j2",                   dest: "/etc/grafana/grafana.ini" }

  # when: not ( bin_files_existed.results | map( attribute='stat.exists') ) is all
  # when: bin_files_existed.stat.exists != True
  # copy: src={{ item }} dest=/root/{{ item }} mode=0644 owner=root group=root


- name: Reload and Start Grafana Services
  systemd:
    daemon_reexec: true
    daemon_reload: true
    name: "{{ item }}"
    enabled: true
    state: started
  register: restart_systemd
  with_items:
    - influxdb
    - grafana-server


- name: Setup PGWatch2 Metrics Database As Default Datasource
  become_user: postgres
  shell: cd {{ item.dir }} ; psql -h localhost -U {{ item.user }} -d {{ item.db }} -f {{ item.file }}
  args:
    executable: /bin/bash
  register: setup_metrics_database
  with_items:
    - { dir: "/etc/pgwatch2/bootstrap", file: "grafana_datasource.sql", user: "pgwatch2_grafana", db: "pgwatch2_grafana" }


- name: Add PGWatch2 Predefined Dashboards to Grafana
  shell: |
    /etc/pgwatch2/grafana-dashboards/import_all.sh
  async: 120
  poll: 5
  register: add_grafana_dashboard


- name: Install Grafana Plugin
  shell: |
    grafana-cli plugins install savantly-heatmap-panel
  async: 120
  poll: 5
  register: install_grafana_plugin

