---
- name: Check OS ( Grafana )
  fail: msg="Not a Red Hat based system!"
  when: ansible_os_family != 'RedHat' or ansible_os_family != 'CentOS' or  ansible_os_family != 'Rocky'


- name: Install GO Language
  import_tasks: install-go.yml
  tags: install
  when: ( go is defined and go == true )


- name: Install prometheus / postgresql_exporter
  import_tasks: install-prometheus.yml
  tags: install
  when: ( prometheus is defined and prometheus == true ) and inventory_hostname in groups['workers']


- name: Install grafana and influx database packages
  import_tasks: install-grafana.yml
  tags: install
  when: ( grafana is defined and grafana == true ) and inventory_hostname in groups['monitors']


- name: Enable SSL on sinlge postgres
  import_tasks: enable-ssl.yml
  tags: install
  when: ( ssl is defined and ssl == true ) and inventory_hostname in groups['monitors']


- name: Uninstall Prometheus / Postgresql Exporter
  import_tasks: uninstall-prometheus.yml
  tags: uninstall
  when: ( prometheus is defined and prometheus == true ) and inventory_hostname in groups['workers']


- name: Unistall grafana and influx database packages
  import_tasks: uninstall-grafana.yml
  tags: uninstall
  when: ( grafana is defined and grafana == true ) and inventory_hostname in groups['monitors']


- name: Uninstall GO language
  import_tasks: uninstall-go.yml
  tags: uninstall
  when: ( go is defined and go == true )


- name: Upgrade grafana for Red Hat / CentOS
  import_tasks: upgrade.yml
  tags: upgrade

