---
- name: Stop and Disable Grafana Services
  systemd:
    daemon_reexec: true
    daemon_reload: true
    name: "{{ item }}"
    enabled: false
    state: stopped
  register: stop_grafana_services
  ignore_errors: true
  with_items:
    - grafana-server
    - influxdb


- name: Delete the Grafana Config Files
  file: path={{ item.dest }} state=absent
  ignore_errors: true
  register: delete_grafana_init_file
  with_items:
    - { src: "grafana.ini.j2",                   dest: "/etc/grafana/grafana.ini" }


- name: Uninstall Pip Modules for Grafana
  shell: |
    pip3 uninstall -y wheel
    pip3 uninstall -y Pillow
    pip3 uninstall -y setuptools_rust
  async: 120
  poll: 5
  ignore_errors: true
  register: uninstall_pip_module


- name: Uninstall Dependent and Grafana RPM Packages
  yum:
    name: "{{ item }}"
    state: present
    # skip_broken: yes
  async: 120
  poll: 5
  ignore_errors: true
  with_items:
    - postgresql-contrib
    - postgresql-devel
    - influxdb2-cli
    - influxdb2
    - grafana-pcp
    - grafana


- name: Delete the influxdb Yum Repo File
  file: path={{ item.dest }} state=absent
  ignore_errors: true
  register: delete_influxdb_repo_file
  with_items:
    - { src: "influxdata.repo.j2",   dest: "/etc/yum.repos.d/influxdata.repo" }

