---
- name: Copy the PGWatch2 RPM Packge
  copy: src=pgwatch2_{{ pgwatch2.major_version }}.{{ pgwatch2.minor_version }}.{{ pgwatch2.patch_version }}_linux_64-bit.rpm dest=/root/pgwatch2_{{ pgwatch2.major_version }}.{{ pgwatch2.minor_version }}.{{ pgwatch2.patch_version }}_linux_64-bit.rpm mode=0644 owner=root group=root


- name: Install PGWatch2 RPM Package
  shell: yum localinstall -y /root/pgwatch2_{{ pgwatch2.major_version }}.{{ pgwatch2.minor_version }}.{{ pgwatch2.patch_version }}_linux_64-bit.rpm


- name: Create the Database Specified in Vars
  become_user: postgres
  vars:
    ansible_python_interpreter: /usr/bin/python2
  postgresql_db: name={{ item }} template='template0' state=present login_host=localhost login_user=postgres login_unix_socket=/tmp
  with_items:
    - "pgwatch2"
    - "pgwatch2_metrics"
    - "pgwatch2_grafana"


- name: Create a User to the PGWatch2 Schema. Typically called PGWatch2, But can be Anything Really, if the Schema Creation File is Adjusted Accordingly.
  become_user: postgres
  vars:
    ansible_python_interpreter: /usr/bin/python2
  postgresql_user: name={{ item.name }} db={{ item.db }} password={{ item.pass }} priv={{ item.priv }} state=present login_host=localhost login_user=postgres login_unix_socket=/tmp
  with_items:
    - { db: 'pgwatch2', name: 'pgwatch2', pass: 'changeme', priv: 'ALL' }
    - { db: 'pgwatch2_grafana', name: 'pgwatch2_grafana', pass: 'changeme', priv: 'ALL' }


- name: Ensure User Does Not Have Unnecessary Permissions
  become_user: postgres
  vars:
    ansible_python_interpreter: /usr/bin/python2
  postgresql_user: name={{ item.name }} role_attr_flags={{ item.role }} state=present login_host=localhost login_user=postgres login_unix_socket=/tmp
  with_items:
    - { name: 'pgwatch2', role: 'SUPERUSER' }
    - { name: 'pgwatch2_grafana', role: 'SUPERUSER' }


- name: Roll Out the PGWatch2 Config Schema and Bootstrap the Metrics Storage DB
  become_user: postgres
  shell: cd {{ item.dir }} ; psql -h localhost -U {{ item.user }} -d {{ item.db }} -f {{ item.file }}
  args:
    executable: /bin/bash
  register: config_metrics_storage_created
  with_items:
    - { dir: "/etc/pgwatch2/sql/config_store", file: "config_store.sql", user: "pgwatch2", db: "pgwatch2" }
    - { dir: "/etc/pgwatch2/sql/config_store", file: "metric_definitions.sql", user: "pgwatch2", db: "pgwatch2" }
    - { dir: "/etc/pgwatch2/sql/metric_store", file: "roll_out_metric_time.psql", user: "pgwatch2", db: "pgwatch2_metrics" }


#- name: Roll Out the PGWatch2 Config Schema and Bootstrap the Metrics Storage DB
#  become_user: postgres
#  shell: cd {{ item.dir }} ; psql -h localhost -U {{ item.user }} -d {{ item.db }} -f {{ item.file }}
#  args:
#    executable: /bin/bash
#  register: config_metrics_storage_created
#  with_items:
#    - { dir: "/etc/pgwatch2/metrics/00_helpers/get_stat_activity/$pgver/", file: "metric.sql", user: "pgwatch2", db: "pgwatch2" }
#    - { dir: "/etc/pgwatch2/metrics/00_helpers/get_stat_replication/$pgver/", file: "metric.sql", db: "pgwatch2" }
#    - { dir: "/etc/pgwatch2/metrics/00_helpers/get_wal_size/$pgver/", file: "metric.sql", db: "pgwatch2" }
#    - { dir: "/etc/pgwatch2/metrics/00_helpers/get_stat_statements/$pgver/", file: "metric.sql", db: "pgwatch2" }
#    - { dir: "/etc/pgwatch2/metrics/00_helpers/get_sequences/$pgver/", file: "metric.sql", db: "pgwatch2" }
#    # export PGUSER=superuser


- name: Install Pip Modules for PGWatch2
  shell: |
    pip3 install setuptools_rust
    python3 -m pip install --upgrade pip
    pip3 install --upgrade setuptools_rust
    python3 -m pip install --upgrade Pillow
    pip3 install wheel
    pip3 install -U -r /etc/pgwatch2/webpy/requirements_pg_metrics.txt
  async: 120
  poll: 5
  register: pip_module_installed


- name: Create the PGWatch2 Web Systemd Unit File
  template: src={{ item.src }} dest={{ item.dest }} owner={{ item.owner }} group={{ item.group }} mode=644 force=yes
  register: etcd_config_created
  with_items:
    - { src: 'pgwatch2-web.systemd.j2', dest: '/etc/systemd/system/pgwatch2-web.service', owner: 'root', group: 'root' }
  when: inventory_hostname in groups['monitors']


- name: Create the PGWatch2 Daemon Systemd Unit File
  template: src={{ item.src }} dest={{ item.dest }} owner={{ item.owner }} group={{ item.group }} mode=644 force=yes
  register: etcd_config_created
  with_items:
    - { src: 'pgwatch2-daemon.systemd.j2', dest: '/etc/systemd/system/pgwatch2-daemon.service', owner: 'root', group: 'root' }
  when: inventory_hostname in groups['workers']


- name: Create the PGWatch2 Instances YAML File
  template: src={{ item.src }} dest={{ item.dest }} owner={{ item.owner }} group={{ item.group }} mode=644 force=yes
  register: pgwatch2_instacnes_file_created
  with_items:
    - { src: 'instances.yaml.j2', dest: '/etc/pgwatch2/config/instances.yaml', owner: 'root', group: 'root' }
  when: inventory_hostname in groups['workers']


- name: Reload and Start Services for PGWatch2 Web and Daemon
  systemd:
    daemon_reexec: true
    daemon_reload: true
    name: "{{ item }}"
    enabled: true
    state: started
  register: systemd_started
  with_items:
    - pgwatch2-web
  when: inventory_hostname in groups['monitors']
  # - pgwatch2-daemon


- name: Reload and Start Services for Daemon
  become: true
  systemd:
    daemon_reexec: true
    daemon_reload: true
    name: "{{ item }}"
    enabled: true
    state: started
  register: systemd_started
  with_items:
    - pgwatch2-daemon
  when: inventory_hostname in groups['workers']
  # - pgwatch2-web

