---
- name: Stop Systemd Service of Workers Instance
  systemd:
    name: pgautofailover
    state: stopped
    daemon_reload: yes
  register: pgautofailover_service_stopped

  # when: uninstall_pkgs == true
  # async: 60
  # poll: 5


- name: Alternative Python Version
  shell: |
    /usr/sbin/update-alternatives --install /usr/bin/python python {{ yum_python_version }} 1
    /usr/sbin/alternatives --set python {{ yum_python_version }}
  register: alternatives_python
  when: ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS' or ansible_distribution == 'Rocky'


- name: Uninstall VMware Postgres RPM Package
  yum:
    name: "{{ common.pgsql_pkg_name }}"
    state: absent
    disable_gpg_check: true
  async: 180
  poll: 5
  vars:
    ansible_python_interpreter: "{{ yum_python_version }}"
  # when: uninstall_pkgs == true


- name: Delete VMware Postgres RPM File
  file:
    path: "{{ common.sudo_user_home_dir }}/{{ pgsql_pkg_name }}.{{ pgsql.arch_type }}.{{ pgsql.bin_type }}"
    state: absent
  when: uninstall_pkgs == true


- name: Delete Configuration Files and Data Directory for VMware Postgres PGAutoFailover
  file:
    path: "{{ item }}"
    state: absent
  register: patroni_config_files_deleted
  with_items: "{{ delete_file_list }}"
  when: uninstall_pkgs == true


- name: Uninstall Prerequesties RPM Packages for VMware Postgres PGAutoFailover
  yum:
    name: "{{ rh_uninstall_pkgs }}"
    state: absent
    skip_broken: yes
  vars:
    ansible_python_interpreter: "{{ yum_python_version }}"
  when: uninstall_dep_pkgs == true


- name: Reload Systemd Daemon
  systemd:
    daemon_reload: yes
  register: sysemd_daemon_reloaded
  async: 60
  poll: 5
  when: uninstall_pkgs == true or uninstall_dep_pkgs == true


- name: Stop and Disable Firewalld
  service:
    name: firewalld
    state: stopped
    enabled: false
  when: enable_firewall == true


- name: Flush Iptables Rules
  shell: ( iptables -F )
  register: iptables_rules_flushed
  when: enable_firewall == true


- name: List Iptables Rules
  shell: ( iptables -nL )
  register: list_iptables_rules
  when: enable_firewall == true


- debug: msg={{ iptables_rules_listed.stdout }}
  tags: print_debug
  when: enable_firewall == true

