---
_ssl:
  ssl_dir: "{{ pgsql.base_dir }}/certs"
  ssl_days: 3660
  ssl_country: "KR"
  ssl_state: "Seoul"
  ssl_location: "Guro"
  ssl_organization: "VMware"
  ssl_organization_unit: "Tanzu"
  ssl_common_name: "jtest.pivotal.io"
  ssl_email: "jomoon@pivotal.io"


# vmware-postgres15-patroni-3.2.0-1.el9.x86_64.rpm
_patroni:
  major_version: "3"
  minor_version: "2"
  patch_version: "0"
  build_version: "1"
  os_version: el9
  arch_type: x86_64
  bin_type: rpm
  bin_path: "{{ common.pgsql_bin_dir }}/patroni"
  ctl_path: "{{ common.pgsql_bin_dir }}/patronictl"
  cluster_name: patclu01
  sync_mode: true
  with_pkgs: rue
  enable_ssl: true
  # false is for pgbackrest, not found yet how does pgbackrest
  # interactive with synchronous mode in patroni cluster
  # sync_mode: on    # one of node will be a Sync Standby role


_etcd:
  major_version: "3"
  minor_version: "3"
  patch_version: "27"
  build_version: ""
  enable_ssl: true
  arch_type: x86_64
  os_version: el9
  bin_type: rpm
  download_bin: false
  blank: " "
  # etcd 3.4.x and 3.5.x does not work for vmware-postgres 15.x versions


# Patroni prerequistes =< vmware-postgres13
# urllib3_ver1: 1.19.1
# urllib3_ver2: 1.21
# six_ver: 1.7
# kazoo_ver: 1.3.1
# python-etc_ver1: 0.4.3
# python-etc_ver2: 0.5
# python-consul_ver: 0.7.0
# click_ver: 4.1
# prettytable_ver: 0.7
# psutil_ver: 2.0.0
# kube_ver1: 2.0.0
# kube_ver2: 7.0.0
# kube_ver3: 4.0
# kube_ver4: 5.0

# RHEL or Rocky Linux 8
# vmware-postgres10-10.21-1.el8.x86_64.rpm            # OK : patroni is included
# vmware-postgres10-10.22-1.el8.x86_64.rpm            # OK : patroni is included
# vmware-postgres10-10.23-1.el8.x86_64.rpm            # OK : patroni is included
# vmware-postgres11-11.16-1.el8.x86_64.rpm            # OK : patroni is included
# vmware-postgres11-11.17-1.el8.x86_64.rpm            # OK : patroni is included
# vmware-postgres11-11.18-1.el8.x86_64.rpm            # OK : patroni is included
# vmware-postgres12-12.11-1.el8.x86_64.rpm            # OK : patroni is included
# vmware-postgres12-12.12-1.el8.x86_64.rpm            # OK : patroni is included
# vmware-postgres12-12.13-1.el8.x86_64.rpm            # OK : patroni is included
# vmware-postgres13-13.7-1.el8.x86_64.rpm             # OK : patroni 2.1.3-1
# vmware-postgres13-13.8-1.el8.x86_64.rpm             # OK : patroni 2.1.4-1
# vmware-postgres13-13.9-1.el8.x86_64.rpm             # OK : patorni 2.1.4-2
# vmware-postgres14-14.3-1.el8.x86_64.rpm             # OK : patroni 2.1.3-1
# vmware-postgres14-14.4-1.el8.x86_64.rpm             # OK : patroni 2.1.3-2
# vmware-postgres14-14.5-1.el8.x86_64.rpm             # OK : patroni 2.1.4-1
# vmware-postgres14-14.6-1.el8.x86_64.rpm             # OK : patroni 2.1.4-2
# vmware-postgres15-15.1-1.el8.x86_64.rpm             # OK : patroni 2.1.4-1

# RHEL or CentOS 7
# pivotal-postgres-10.10-3.el7.x86_64.rpm            # - OK : patroni is included
# pivotal-postgres-10.10-4.el7.x86_64.rpm            # - OK : patroni is included
# pivotal-postgres-10.10-5.el7.x86_64.rpm            # - OK : patroni is included
# pivotal-postgres-10.11-1.el7.x86_64.rpm            # - OK : patroni is included
# vmware-postgres-10.12-2.el7.x86_64.rpm             # - OK : patroni is included
# vmware-postgres-10.12-3.el7.x86_64.rpm             # - OK : patroni is included
# vmware-postgres-10.14-2.el7.x86_64.rpm             # - OK : patroni is included
# vmware-postgres-10.15-0.el7.x86_64.rpm             # - OK : patroni is included
# vmware-postgres-10.16-1.el7.x86_64.rpm             # - OK : patroni is included
# vmware-postgres-10.17-0.el7.x86_64.rpm             # - OK : patroni is included
# vmware-postgres10-10.18-0.el7.x86_64.rpm           # - OK : patroni is included
# vmware-postgres10-10.18-1.el7.x86_64.rpm           # - OK : patroni is included
# vmware-postgres10-10.19-0.el7.x86_64.rpm           # - OK : patroni is included
# vmware-postgres10-10.20-1.el7.x86_64.rpm           # - OK : patroni is included
# vmware-postgres10-10.21-1.el7.x86_64.rpm           # - OK : patroni is included
# vmware-postgres10-10.22-1.el7.x86_64.rpm           # - OK : patroni is included
# vmware-postgres10-10.23-1.el7.x86_64.rpm           # - OK : patroni is included
# pivotal-postgres-11.1-1.el7.x86_64.rpm             # - patroni is not included in this version
# pivotal-postgres-11.2-1.el7.x86_64.rpm             # - patroni is not included in this version
# pivotal-postgres-11.3-1.el7.x86_64.rpm             # - patroni is not included in this version
# pivotal-postgres-11.4-1.el7.x86_64.rpm             # - patroni is not included in this version
# pivotal-postgres-11.5-3.el7.x86_64.rpm             # - OK : patroni is included
# pivotal-postgres-11.5-4.el7.x86_64.rpm             # - OK : patroni is included
# pivotal-postgres-11.5-5.el7.x86_64.rpm             # - OK : patroni is included
# pivotal-postgres-11.6-1.el7.x86_64.rpm             # - OK : patroni is included
# vmware-postgres-11.7-2.el7.x86_64.rpm              # - OK : patroni is included
# vmware-postgres-11.7-3.el7.x86_64.rpm              # - OK : patroni is included
# vmware-postgres-11.9-2.el7.x86_64.rpm              # - OK : patroni is included
# vmware-postgres-11.10-0.el7.x86_64.rpm             # - OK : patroni is included
# vmware-postgres-11.11-1.el7.x86_64.rpm             # - OK : patroni is included
# vmware-postgres-11.12-0.el7.x86_64.rpm             # - OK : patroni is included
# vmware-postgres11-11.13.0.el7.x86_64.rpm           # - OK : patroni is included
# vmware-postgres11-11.13.1.el7.x86_64.rpm           # - OK : patroni is included
# vmware-postgres11-11.14.1.el7.x86_64.rpm           # - OK : patroni is included
# vmware-postgres11-11.15.0.el7.x86_64.zip           # - OK : patroni is included
# vmware-postgres11-11.15.1.el7.x86_64.zip           # - OK : patroni is included
# vmware-postgres11-11.17-1.el7.x86_64.rpm           # - OK : patroni is included
# vmware-postgres11-11.18-1.el7.x86_64.rpm           # - OK : patroni is included
# vmware-postgres-12.3-1.el7.x86_64.rpm              # - OK : patroni is included
# vmware-postgres-12.4-2.el7.x86_64.rpm              # - OK : patroni is included
# vmware-postgres-12.5-0.el7.x86_64.rpm              # - OK : patroni is included
# vmware-postgres-12.6-1.el7.x86_64.rpm              # - OK : patroni is included
# vmware-postgres-12.7-0.el7.x86_64.rpm              # - OK : patroni is included
# vmware-postgres12-12.8-1.el7.x86_64.rpm            # - OK : patroni is included
# vmware-postgres12-12.10-1.el7.x86_64.rpm           # - OK : patroni is included
# vmware-postgres12-12.11-1.el7.x86_64.rpm           # - OK : patroni is included
# vmware-postgres12-12.12-1.el7.x86_64.rpm           # - OK : patroni is included
# vmware-postgres12-12.13-1.el7.x86_64.rpm           # - OK : patroni is included
# vmware-postgres-13.3-0.el7.x86_64.rpm              # - patroni is not included in this version
# vmware-postgres13-13.4-0.el7.x86_64.rpm            # - patroni is not included in this version
# vmware-postgres13-13.5-1.el7.x86_64.rpm            # - patroni is not included in this version
# vmware-postgres13-13.6-0.el7.x86_64.rpm            # - patroni is not included in this version
# vmware-postgres13-13.7-1.el7.x86_64.rpm            # - OK : patroni 2.1.3-1
# vmware-postgres13-13.8-1.el7.x86_64.rpm            # - OK : patroni 2.1.4-1
# vmware-postgres13-13.9-1.el7.x86_64.rpm            # - OK : patroni 2.1.4-2
# vmware-postgres14-14.0-0.el7.x86_64.rpm            # - OK : patroni 2.1.3-1 although patroni is not included in this version
# vmware-postgres14-14.1-1.el7.x86_64.rpm            # - OK : patroni 2.1.3-1 although patroni is not included in this version
# vmware-postgres14-14.2-1.el7.x86_64.rpm            # - OK : patroni 2.1.3-1 although patroni is not included in this version
# vmware-postgres14-14.3-1.el7.x86_64.rpm            # - OK : patroni 2.1.3-1
# vmware-postgres14-14.4-1.el7.x86_64.rpm            # - OK : patroni 2.1.3-2
# vmware-postgres14-14.5-1.el7.x86_64.rpm            # - OK : patroni 2.1.4-1
# vmware-postgres14-14.6-1.el7.x86_64.rpm            # - OK : patroni 2.1.4-2
# vmware-postgres15-15.1-1.el7.x86_64.rpm            # - OK : patroni 2.1.4-1
# vmware-postgres15-15.1-1.el8.x86_64.rpm            # - OK : patroni 2.1.4-1


# config_firewall: true
# install_dep_pkgs: true
# install_pip_module: true
# install_pkgs: true
# install_etcd: true
# config_env: true

# enable_ssl: false

# config_patroni: true
# add_users: true
# stop_patroni_service: true
# remove_firewall_config: true
# uninstall_dep_pkgs: true
# uninstall_pkgs: true
# remove_env_config: true
# uninstall_pip_module: true

