---
# Destroy VMware Postgres Patroni Cluster
#
#- name: Define package names for VMware Postgres/Patroni/ETCD
#  set_fact:
#    pgsql_pkg_name: "{{ common.pgsql_pkg_name }}-{{ pgsql.major_version }}.{{ pgsql.minor_version }}-{{ pgsql.patch_version }}.{{ pgsql.os_version }}"
#    patroni_pkg_name: "{{ common.pgsql_pkg_name }}-patroni-{{ patroni.major_version }}.{{ patroni.minor_version }}.{{ patroni.patch_version }}"
#    etcd_pkg_name: "etcd-{{ etcd.major_version }}.{{ etcd.minor_version }}.{{ etcd.patch_version }}"

    # pgsql_pkg_name: "{{ common.pgsql_pkg_name }}-{{ pgsql.major_version }}.{{ pgsql.minor_version }}-{{ pgsql.patch_version }}.{{ pgsql.os_version }}.{{ pgsql.arch_type }}.{{ pgsql.bin_type }}"
    # patroni_pkg_name: "{{ common.pgsql_pkg_name }}-patroni-{{ patroni.major_version }}.{{ patroni.minor_version }}.{{ patroni.patch_version }}-{{ patroni.build_version }}.{{ patroni.os_version }}.{{ patroni.arch_type }}.{{ patroni.bin_type }}"
    # etcd_pkg_name: "etcd-{{ etcd.major_version }}.{{ etcd.minor_version }}.{{ etcd.patch_version }}-{{ etcd.build_version }}.{{ etcd.os_version }}.x86_64.rpm"

# 41-stop-patroni-service.yml
- name: Stop services for patroni and etcd
  systemd:
    name: patroni
    enabled: no
    state: stopped
  register: patroni_etcd_service_stopped
  until: patroni_etcd_service_stopped is succeeded
  retries: 3
  with_items:
    - etcd
    - patroni
  ignore_errors: yes
  when: uninstall_pkgs

#
- name: Kill etcd process
  shell: ( killall etcd )
  register: etcd_processes_killed
  ignore_errors: yes
  when: uninstall_pkgs

# 42-uninstall-pkgs.yml
- name: Uninstall Patroni RPM Package
  yum:
    name: "{{ item }}"
    state: absent
  register: patroni_rpm_packages_uninstalled
  with_items:
    - "{{ patroni_pkg_name }}"
  when: patroni.with_pkgs == true and uninstall_pkgs == true

#
- name: Uninstall VMware Postgres RPM packages
  yum:
    name: "{{ item }}"
    state: absent
  register: vmware_postgres_rpm_packages_deleted
  with_items:
    - "{{ pgsql_pkg_name }}"
    - "vmware-postgres"
  when: uninstall_pkgs

#
- name: Delete the vmwawre-postgres{{ pgsql.major_version }}-paroni rpm file
  file:
    path: /home/jomoon/{{ patroni_pkg_name }}-{{ patroni.build_version }}.{{ patroni.os_version }}.x86_64.rpm
    state: absent
  register: patroni_rpm_packages_deleted
  ignore_errors: true
  when: patroni.with_pkgs == true and uninstall_pkgs == true


#
- name: Delete the vmwawre-postgres rpm file
  file:
    path: /home/jomoon/{{ pgsql_pgk_name }}.x86-64.rpm
    state: absent
  register: vmware_postgres_rpm_packages_deleted
  when: uninstall_pkgs == true


# 43-uninstall-pip-module.yml
- name: Unstall Patroni PIP module
  become_user: root
  shell: (  export PATH=$PATH:/usr/local/bin && pip3 uninstall {{ item }} -y )
  register: pip3_patroni_uninstalled
  ignore_errors: true
  with_items: "{{ rh8_pip3_module }}"
  when: uninstall_pip_module == true and hostvars[inventory_hostname].ansible_distribution_major_version|int >= 8


- name: Uninstall Pip3 Modules for higher versions than vmware-postgres {{ pgsql.major_version }}
  shell: ( export PATH=$PATH:/usr/local/bin && pip3 uninstall {{ item.pip3_name }} -y )
  register: extra_pip3_modules_for_higher_than_vmware_postgres_14_uninstalled
  ignore_errors: true
  with_items: "{{ pg14_pip3_module }}"
  when: uninstall_pip_module and pgsql.major_version >= 14


- name: Uninstall Pip3 Modules for ealier versions than vmware-postgres{{ pgsql.major_version }}
  shell: ( export PATH=$PATH:/usr/local/bin && pip3 uninstall {{ item.pip3_name }} -y )
  register: extra_pip3_modules_for_earlier_than_vmware_postgres_13_uninstalled
  ignore_errors: yes
  with_items: "{{ pip13_pip3_module }}"
  when: uninstall_pip_module and pgsql.major_version >= 13


- name: Uninstall Common Pip3 Modules ( typing/etcd and so on )
  shell: ( export PATH=$PATH:/usr/local/bin && pip3 uninstall {{ item }} -y )
  register: common_pip3_modules_uninstalled
  ignore_errors: true
  with_items: "{{ prereq_pip3_module }}"
  when: uninstall_pip_module

#    - "psycopg2"
#    - "etcd"
#    - "etcd3"
#    - "python-etcd"
#    - "typing"
#    - "ydiff"
#    - "psutil"
#    - "prettytable"
#    - "click"
#    - "setuptools-rust"
#    - "wheel"
#    - "pip"


# 44-uninstall-dep-pkgs.yml
- name: Uninstall RPM packages of the etcd and Patroni prerequisites
  yum:
    name: "{{ item }}"
    state: absent
    skip_broken: yes
  register: prereq_rpm_packages_of_patroni_deleted
  ignore_errors: true
  with_items: "{{ rh7_dep_pkgs }}"
  when: uninstall_dep_pkgs == true and hostvars[inventory_hostname].ansible_distribution_major_version|int <= 7
  # - python34-setuptools

#
- name: Unnstall Python 3.9 for RHEL or CentOS {{  hostvars[inventory_hostname].ansible_distribution_major_version }}
  yum:
    name: "{{ item }}"
    state: absent
    skip_broken: yes
  register: python39_installed
  ignore_errors: true
  with_items: "{{ rh8_python_pkgs }}"
  when: uninstall_dep_pkgs == true and hostvars[inventory_hostname].ansible_distribution_major_version|int <= 8


# xxxxx need to check
- name: Uninstall prerequisites RPM packages of the ETCD and Patroni
  yum:
    name: "{{ item }}"
    state: absent
    skip_broken: yes
  register: prereq_rpm_packages_of_patroni_deleted
  ignore_errors: true
  with_items: "{{ rh_common_dep_pkgs }}"
  when: uninstall_dep_pkgs == true

  # and hostvars[inventory_hostname].ansible_distribution_major_version|int <= 7
  # - python34-setuptools
#
- name: Unnstall Python 3.11 for RHEL or CentOS {{  hostvars[inventory_hostname].ansible_distribution_major_version }}
  yum:
    name: "{{ item }}"
    state: absent
    skip_broken: yes
  with_items: "{{ rh9_python_pkgs }}"
  register: python311_installed
  ignore_errors: true
  when: uninstall_dep_pkgs == true and hostvars[inventory_hostname].ansible_distribution_major_version|int >= 9

#
#- name: Delete the dependencies file of etcd
#  become_user: postgres
#  file:
#    path: /var/lib/pgsql/requirements.txt
#    state: absent
#  register: patroni_prereq_uninstalled_of_etcd_deleted
#  ignore_errors: true
#  when: uninstall_pip_module

# 45-remove-config-files.yml
- name: Delete configuration files for patroni and systemd
  file:
    path: "{{ item }}"
    state: absent
  register: patroni_config_files_deleted
  ignore_errors: true
  with_items:
    - "/var/lib/pgsql/patroni.yml"
    - "/etc/systemd/system/patroni.service"
    - "/var/lib/pgsql/postgresql0.yml"
    - "/var/lib/pgsql/patroni_member.log"
    - "/var/lib/pgsql/etcd.yml"
    - "/var/lib/pgsql/etcd_logfile"
    - "/var/lib/pgsql/.bash_profile"
    - "/etc/etcd/etcd.conf"
    - "/usr/bin/etcd"
    - "/usr/bin/etcdctl"
  when: remove_patroni_config

#
- name: Delete data directories
  file:
    path: "/var/lib/pgsql/{{ item }}"
    state: absent
  register: data_directories_deleted
  ignore_errors: true
  with_items:
    - "backups"
    - "data"
    - "patroni_data"
    - "wal_archive"
    - "pgpass0"
    - "requirements.txt"
  when: uninstall_pkgs

#
- name: Delete old patroni data directory for patroni cluster
  shell: rm -rf /var/lib/pgsql/.local /var/lib/pgsql/.cache /var/lib/pgsql/patroni_data_*
  register: backup_hidden_data_directories_deleted
  ignore_errors: true
  when: uninstall_pkgs


# 46-disable-firewalld-config.yml
- name: List iptables rules
  become_user: root
  shell: ( iptables -nL )
  register: iptables_rules_listed
  ignore_errors: true
  when: remove_firewall_config

#
- name: Flush iptables rules
  become_user: root
  shell: ( iptables -F )
  register: iptables_rules_flushed
  ignore_errors: true
  when: remove_firewall_config

#
- name: Stop and disable firewalld
  systemd:
    name: firewalld
    state: stopped
    enabled: false
  register: firewalld_service_stopped
  ignore_errors: true
  when: remove_firewall_config

- debug: msg={{ iptables_rules_listed.stdout }}
  tags:
    - print_debug
  when: remove_firewall_config
