single:
	@if [ "${r}" = "install" ]; then\
		ansible-playbook --ssh-common-args='-o UserKnownHostsFile=./known_hosts' -i ./ansible-hosts-single -u ${USERNAME} setup-single.yml --tags='install';\
	elif [ "${r}" = "uninstall" ]; then\
		ansible-playbook --ssh-common-args='-o UserKnownHostsFile=./known_hosts' -i ./ansible-hosts-single -u ${USERNAME} setup-single.yml --tags='uninstall';\
	else\
		echo "No Actions for Installing and Uninstallinig VMware Postgres Single Instance";\
		exit;\
	fi

