---
- name: Create the Database Specified in Vars
  become_user: postgres
  postgresql_db: name={{ pgsql.db_name }}
       template='template0'
       state=present
       login_unix_socket=/tmp
  register: create_database
  vars:
    ansible_python_interpreter: "{{ yum_python_version }}"


- name: Ensure User Has Access to the New Database
  become_user: postgres
  postgresql_user: db={{ pgsql.db_name }}
       name={{ pgsql.db_user }}
       password={{ pgsql.db_password }}
       priv=ALL
       state=present
       login_unix_socket=/tmp
  register: create_user
  vars:
    ansible_python_interpreter: "{{ yum_python_version }}"


- name: Ensure User Does Not Have Unnecessary Permissions
  become_user: postgres
  postgresql_user: name={{ pgsql.db_user }}
       role_attr_flags=SUPERUSER,CREATEDB,CREATEROLE,INHERIT,LOGIN,REPLICATION
       state=present
       login_unix_socket=/tmp
  register: enroll_permission
  vars:
    ansible_python_interpreter: "{{ yum_python_version }}"

# role_attr_flags=NOSUPERUSER,NOCREATEDB
# role_attr_flags
# [NO]SUPERUSER
# [NO]CREATEROLE
# [NO]CREATEDB
# [NO]INHERIT
# [NO]LOGIN
# [NO]REPLICATION
# [NO]BYPASSRLS
# https://docs.ansible.com/ansible/2.8/modules/postgresql_user_module.html

