---
# Install Sinlge Postgres Database
#
- name: initialize your PostgresL instance
  become: true
  become_user: postgres
  shell: ( source /var/lib/pgsql/.bash_profile ; {{ bin_dir }}/initdb -D /var/lib/pgsql/data )
  register: postgres_instance_initialized
  args:
    chdir: "/var/lib/pgsql"
    executable: /bin/bash

#
- name: Create a single non-HA Postgres server
  become: true
  become_user: postgres
  shell: ( source /var/lib/pgsql/.bash_profile ; {{ bin_dir }}/postgres -D /var/lib/pgsql/data > /var/lib/pgsql/data/logfile 2>&1 & )
  register: postgres_instance_created
  args:
    chdir: "/var/lib/pgsql"
    executable: /bin/bash

#
- name: Verify that pg_auto_failover/postgres was installed properly
  become: true
  become_user: postgres
  shell: ( source /var/lib/pgsql/.bash_profile ; {{ bin_dir }}/psql -c "select version()" )
  register: postgres_install_verified
  args:
    chdir: "/var/lib/pgsql"
    executable: /bin/bash

- name: Verify that postgres was installed properly
  become: true
  become_user: postgres
  shell: ( source /var/lib/pgsql/.bash_profile ; {{ bin_dir }}/pg_ctl -V )
  register: pg_ctl_install_verified
  args:
    chdir: "/var/lib/pgsql"
    executable: /bin/bash

#- name: Getting process IDs of the pg_autoctl process
#  pids:
#    name: pg_autoctl
#  register: pids_of_pg_autoctl
#  ignore_errors: yes

#- name: Printing the process IDs obtained
#  debug:
#    msg: "PIDS of pg_autoctl:{{pids_of_pg_autoctl.pids|join(',')}}"
#  ignore_errors: yes
#  tags:
#    - print_debug

# - name: Getting process IDs of processes matching pattern
#  community.general.pids:
#    pattern: myapp(2(\.7)?|3(\.6)?)?\s+myapp\.py
#  register: myapp_pids

#
- name: Insert executable binary path into .bashrc for VMware Postgres {{ major_version }}
  become: true
  become_user: postgres
  lineinfile:
    path: "{{ item }}"
    line: "export PATH={{ bin_dir }}:$PATH"
  with_items:
    - "/var/lib/pgsql/.bash_profile"
    - "/home/postgres/.bashrc"

  #  path: /var/lib/pgsql/.bashrc

#
- name: Grant user access from network 192.168.0.0/24 access for access with cert authentication.
  become: true
  become_user: postgres
  postgresql_pg_hba:
    dest: /var/lib/pgsql/data/pg_hba.conf
    contype: host
    users: all
    source: 192.168.0.0/24
    databases: all
    method: trust

#
- name: Replace database directory
  become: true
  become_user: postgres
  replace:
    path: /var/lib/pgsql/.bash_profile
    regexp: '^(.*)PGDATA=(.*)$'
    replace: 'PGDATA=//var/lib/pgsql/data'
    backup: yes

#
- name: Verify the current state of postgres instance
  become: true
  become_user: postgres
  shell: ( ps -ef | grep postgres )
  register: postgres_instance_state_verified
  # shell: ( ps -ef | grep postgres )

#
- name: Verify the current state of postgres
  become: true
  become_user: postgres
  shell: ( source /var/lib/pgsql/.bash_profile ; {{ bin_dir }}/psql -c "\l" )
  register: postgres_state_verified
  args:
    chdir: "/var/lib/pgsql"
    executable: /bin/bash

#
- debug: msg={{ postgres_state_verified }}
  tags:
    - print_debug
