---
- name: Check OS ( Single )
  fail: msg="Not a Red Hat based system!"
  when: ansible_os_family != 'RedHat' or ansible_os_family != 'CentOS' or  ansible_os_family != 'Rocky'


- name: Set Facts for Package Name and List and Network Range
  import_tasks: set-facts.yml
  tags: install, uninstall, init, enable, disable, config, stop, add


- name: Stop and Diable Firewalld and SELinux
  import_tasks: security/disable-security.yml
  tags: disable, install
  when: ( security is defined and security == true ) or ( single_all is defined and single_all == true )


- name: Install Common Prerequisties and VMware Postgres RPM Packages
  import_tasks: install-pkgs.yml
  tags: install
  when: ( pkgs is defined and pkgs == true ) or ( single_all is defined and single_all == true )


- name: Initialize VMware Postgres Instance
  import_tasks: init-pgsql.yml
  tags: init, install
  when: ( postgres is defined and postgres == true ) or ( single_all is defined and single_all == true )


- name: Create Database and Users
  import_tasks: add-users.yml
  tags: install, add
  when: ( user is defined and user == true ) or ( single_all is defined and single_all == true )


- name: Enable SSL for Single VMware Postgres
  import_tasks: enable-ssl.yml
  tags: enable, config, install
  when: ( ssl is defined and ssl == true ) or ( single_all is defined and single_all == true )


- name: Check the status of Single VMware Postgres
  import_tasks: check-status.yml
  tags: install
  when: ( single_all is defined and single_all == true )


- name: Stop and Disable PostgreSQL
  import_tasks: stop-pgsql-service.yml
  tags: uninstall, destroy, delete, stop
  when: ( service is defined and service == true ) or ( single_all is defined and single_all == true )


- name: Uninstall Common Prerequisties and VMware Postgres RPM Packages
  import_tasks: uninstall-pkgs.yml
  tags: uninstall
  when: ( pkgs is defined and pkgs == true ) or ( single_all is defined and single_all == true )


- name: Enable Firewalld and SELinux
  import_tasks: security/enable-security.yml
  tags: enable, uninstall
  when: ( security is defined and security == true ) or ( single_all is defined and single_all == true )


- name: Remove config files of environment for Single VMware Postgres
  import_tasks: remove-config-files.yml
  tags: uninstall, remove
  when: ( files is defined and files == true ) or ( single_all is defined and single_all == true )


- name: Upgrade RPM Packages for Single VMware Postgres
  import_tasks: upgrade.yml
  tags: upgrade

