---
# Install VMWare Postgres for Red Hat / CentOS

# for now fail if it's not a Red Hat based system
- name: Check OS ( GPDB )
  fail: msg="Not a Red Hat based system!"
  when:
    - inventory_hostname in groups['all']
    - ansible_os_family != 'RedHat' or ansible_os_family != 'CentOS' or  ansible_os_family != 'Rocky'

#
- name: Installation common package for single postgres
  import_tasks: install-common.yml
  tags: install
  when: inventory_hostname in groups['all']

#
- name: Installation single postgres
  import_tasks: install-postgres.yml
  tags: install
  when: inventory_hostname in groups['all']

#
- name: Enable SSL on sinlge postgres
  import_tasks: enable-ssl.yml
  tags: install
  when: enable_ssl == true and inventory_hostname in groups['all']

#
- name: Check the status of sinlge postgres
  import_tasks: check-status.yml
  tags: install
  when: inventory_hostname in groups['all']

#
- name: Uninstallation of sinlge postgres for Red Hat / CentOS
  import_tasks: uninstall.yml
  tags: uninstall
  when: inventory_hostname in groups['all']

#
- name: Upgrade of single postgres for Red Hat / CentOS
  import_tasks: upgrade.yml
  tags: upgrade
  when: inventory_hostname in groups['all']
