---
- name: Delete Variables and Configuration Files
  file:
    path: "{{ item }}"
    state: absent
  register: delete_config_files
  ignore_errors: true
  with_items:
    - "/var/lib/pgsql/logfile"
    - "/var/lib/pgsql/.bash_profile"
    - "/var/lib/pgsql/backups"
    - "/var/lib/pgsql/data"
    - "/var/lib/pgsql/wal_archive"
    - "/var/lib/pgsql/pgpass0"
    - "/var/lib/pgsql"

