---
- name: Uninstall VMware Postgres RPM Package
  package:
    name: "{{ pgsql_pkg_name }}"
    state: absent
    disable_gpg_check: true
  vars:
    ansible_python_interpreter: "{{ yum_python_version }}"


- name: Delete VMware Postgres RPM Package File
  file:
    path: "{{ common.sudo_user_home_dir }}/{{ pgsql_pkg_name }}.{{ pgsql.arch_type }}.{{ pgsql.bin_type }}"
    state: absent


- name: Delete Configuration Files and Data Directory for VMware Postgres
  file:
    path: "{{ item }}"
    state: absent
  register: delete_postgres_config_files
  with_items: "{{ delete_file_list }}"


- name: Uninstall Prerequesties RPM Packages for VMware Postgres
  package:
    name: "{{ rh_uninstall_pkgs }}"
    state: absent
    skip_broken: yes
  vars:
    ansible_python_interpreter: "{{ yum_python_version }}"


- name: Reload Systemd Daemon
  systemd:
    daemon_reload: yes
  register: reload_sysemd_daemon
  async: 60
  poll: 5


- name: Alternative Python Version
  shell: |
    /usr/sbin/update-alternatives --install /usr/bin/python python {{ yum_python_version }} 1
    /usr/sbin/alternatives --set python {{ yum_python_version }}
  register: alternatives_python3
  when: ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS' or ansible_distribution == 'Rocky'

