---
- name: Check OS ( Postgres BDR )
  fail: msg="Not a Red Hat based system!"
  when: ansible_os_family != 'RedHat'


- name: Install PostgreSQL 9.4 BDR
  include: install.yml
  tags: install


- name: Uninstall PostgreSQL 9.4 BDR
  include: uninstall.yml
  tags: uninstall


- name: Upgrade PostgreSQL 9.4 BDR
  include: upgrade.yml
  tags: upgrade

