rh_common_dep_pkgs: "@Development tools,epel-release,perl,perl-libs,firewalld,readline-devel,libicu-devel,rsyslog,rsync,postgresql-devel,
python3,python3-libs,python3-devel,python3-pip,python3-setuptools,python3-rpm-generators,gcc"

remove_rh_common_dep_pkgs: "readline-devel,libicu-devel,rsyslog,rsync,postgresql-devel,python3-setuptools,python3-rpm-generators,python3-PyYAML,
python3-pathspec,python3-psycopg2,,epel-release"

rh7_dep_pkgs: "tk"
rh8_dep_pkgs: "tk"
rh9_dep_pkgs: "tk"

rh7_python_pkgs: "python-psycopg2"
rh8_python_pkgs: "python39,python39-pip,python39-libs,python39-devel,python3-psycopg2,selinux-policy-targeted"
rh9_python_pkgs: "python3.11,python3.11-pip,python3.11-libs,python3.11-devel,python3-psycopg2,selinux-policy-targeted"


delete_file_list:
  - "/var/lib/pgsql/ha"
  - "/var/lib/pgsql/{{ pgsql.db_name }}"
  - "/var/lib/pgsql/data"
  - "/var/lib/pgsql/backup"
  - "/var/lib/pgsql/backups"
  - "/var/lib/pgsql/.local"
  - "/var/lib/pgsql/.bash_profile"
  - "/home/postgres/.local"
  - "/home/postgres/.ansible_async"
  - "/var/lib/pgsql/monitor"
  - "/var/lib/pgsql/pgautofailover.service"
  - "/var/lib/pgsql/certs"


#  - "/var/lib/pgsql/pgautofailover.service"
# - "/home/postgres/"
# - "/var/lib/pgsql"
# - "/var/lib/pgsql/.bash_profile"

