---
- name: Stop and Disable Firewalld
  service:
    name: firewalld
    state: stopped
    enabled: no


- name: Flush IPTables Rules
  shell: |
    iptables -F
  register: flush_iptables_rules


- name: List IPTables Rules
  shell: |
    iptables -nL
  register: list_iptables_rules
- debug: msg={{ list_iptables_rules.stdout }}

