rh_common_dep_pkgs: "@Development tools,epel-release,perl,perl-libs,firewalld,readline-devel,libicu-devel,rsyslog,rsync,postgresql-devel,
python3,python3-libs,python3-devel,python3-pip,python3-setuptools,python3-rpm-generators,
gcc"

remove_rh_common_dep_pkgs: "readline-devel,libicu-devel,rsyslog,rsync,postgresql-devel,
python3-setuptools,python3-rpm-generators,python3-PyYAML,
gcc,epel-release"
# python3-pathspec,python3-psycopg2,

rh7_dep_pkgs: "tk"
# python-psycopg2,etcd,yamllint"
rh8_dep_pkgs: "tk"
rh9_dep_pkgs: "tk"

rh7_python_pkgs: "python-psycopg2"
# python3-PyYAML,python3-psycopg2,
rh8_python_pkgs: "python39,python39-pip,python39-libs,python39-devel"
# python3-pathspec"
rh9_python_pkgs: "python3.11,python3.11-pip,python3.11-libs,python3.11-devel"

#  - "setuptools-rust"
common_pip3_module:
  - "cdiff"
  - "typing"
  - "wheel"
  - "setuptools==58.2.0"                  # This version allow to install requirements.txt in EL 9.x version
  - "-r /var/lib/pgsql/requirements.txt"

# Prerequesties for Patroni
prereq_pip3_module:
  - "tzlocal"
  - "requests"
  - "ydiff"
  - "psutil"
  - "prettytable"
  - "click"
  - "python-etcd"
  - "psycopg2"

pg13_pip3_module:
  - { pg_ver: 13, cond: "<=", pip3_name: "psycopg2-binary" }

pg14_pip3_module:
  - { pg_ver: 14, cond: ">=", pip3_name: "pyopenssl" }
  - { pg_ver: 14, cond: ">=", pip3_name: "pyrsistent==0.16.0" }

# For patroni
rh8_pip3_module:
  - "patroni==3.0.4"

# For patroni
rh9_pip3_module:
  - "patroni==3.0.4"

