---
- name: Disable SSL on Workers
  become_user: postgres
  shell: |
    export PGDATA=/var/lib/pgsql/ha
    {{ common.pgsql_bin_dir }}/pg_autoctl disable ssl
  register: enable_ssl_workers


- name: Restart PGAutoFailover Service to Apply SSL Changes
  become_user: postgres
  shell: |
    sudo systemctl restart pgautofailover
  register: restart_pgautofailover

