---
- name: Create SSL Keys
  import_tasks: ssl/create-ssl-keys.yml
  tags: create, install
  when: ( ssl is defined and ssl == true )


- name: Disable SSL on Monitor
  import_tasks: ssl/disable-ssl-monitor.yml
  tags: disable, uninstall
  when: (( monitor is defined and monitor == true ) and ( ssl is defined and ssl == true )) and inventory_hostname in groups['monitor']


- name: Enable SSL on Monitor
  import_tasks: ssl/enable-ssl-monitor.yml
  tags: enable, install
  when: (( monitor is defined and monitor == true ) and ( ssl is defined and ssl == true )) and inventory_hostname in groups['monitor']


- name: Disable SSL on Workers
  import_tasks: ssl/disable-ssl-workers.yml
  tags: disable, uninstall
  when: (( workers is defined and workers == true ) and ( ssl is defined and ssl == true )) and inventory_hostname in groups['workers']


- name: Enable SSL on Workers
  import_tasks: ssl/enable-ssl-workers.yml
  tags: enable, install
  when: (( workers is defined and workers == true ) and ( ssl is defined and ssl == true )) and inventory_hostname in groups['workers']

