---
- name: Check OS ( PGBackRest )
  fail: msg="Not a Red Hat based system!"
  when: ansible_os_family != 'RedHat'


- name: Install VMware Postgres PGBackRest
  import_tasks: install.yml
  tags: install


- name: Uninstall VMware Postgres PGBackRest
  import_tasks: uninstall.yml
  tags: uninstall


- name: Upgrade VMware Postgres PGBackRest
  import_tasks: upgrade.yml
  tags: upgrade

