---
- name: Stop and Disable Firewalld
  become: true
  service:
    name: firewalld
    state: stopped
    enabled: false


- name: Flush IPTables Rules
  become: true
  become_user: root
  shell: ( iptables -F )
  register: iptables_rules_flushed


- name: List IPTables Rules
  become: true
  become_user: root
  shell: ( iptables -nL )
  register: iptables_rules_listed


- debug: msg={{ iptables_rules_listed.stdout }}
  tags:
    - print_debug

